snyk/driftctl

- doc/cmd/scan/iac_source.md
Add documentation on required permissions for S3 remote state
> Add policy doc for remote s3 state

- .github/stale.yml
> Add stale app

- README.md
| 🔗 Related issues | #26 
Update main readme to add run example using aws profile and credentials
> Updated documentation usage for aws creds

- .github/ISSUE_TEMPLATE/documentation.md
> Add doc issue template

- pkg/cmd/scan.go
> fix minor typo reported by user

- doc/cmd/scan/filter.md
- pkg/filter/driftignore.go
- pkg/filter/testdata/drift_ignore_fields/.driftignore
> Make driftignore fields case-insensitive

- README.md
| 🔗 Related issues | #82 
- Add Homebrew installation guidelines
- Add Homebrew badge
- Reformat headings
> Update README with Homebrew installation guidelines with its badge

- .circleci/config.yml
| 🔗 Related issues | #90
CircleCI step to bump driftctl homebrew formula !
> Homebrew bump driftctl formula CircleCI

- pkg/analyser/analyzer.go
A weakness was introduced in the analyzer when adding support for computed field.
> Fix a weakness in analyzer

- README.md
> Move documentation section above in the readme

- test/acceptance/result.go
> Display analysis summary when infra not in sync in acc tests

- doc/cmd/scan/supported_resources/aws.md
Up and running CloudFormation launch stack button to create our limited permission role.
> Doc to use our custom role CloudFormation template

- pkg/driftctl.go
- pkg/middlewares/aws_default_igw_route.go
- pkg/middlewares/aws_default_igw_route_test.go
| 🔗 Related issues | #138
Added middleware
> Add middleware for default gateway route

- doc/README.md
- doc/cmd/completion/script.md
- pkg/cmd/completion.go
- pkg/cmd/completion_test.go
- pkg/cmd/driftctl.go
- pkg/cmd/driftctl_test.go
| 🔗 Related issues | #129
Completion command for bash, zsh, fish and powershell !
> Driftctl completion command

- pkg/iac/terraform/state/test/iam_user_multiple/terraform.tfstate
- pkg/resource/aws/aws_iam_user_ext.go
> Fix false positive drift on aws_iam_user

- doc/README.md
- pkg/cmd/driftctl.go
- pkg/cmd/driftctl_test.go
| 🔗 Related issues | #162
This might not be new feature :neutral_face:
This is my first contribution for this awesome tool! :star2:
I fixed #162.
Please review my commit!
> Make DCTL_NO_VERSION_CHECK accept any value

- README.md
> Add contributions country flags

- .circleci/config.yml
- pkg/resource/aws/testdata/acc/aws_security_group/.terraform.lock.hcl
Success notification
Failure notification
Example of succeeded run : https://app.circleci.com/pipelines/github/cloudskiff/driftctl/399/workflows/88afca8b-5201-44df-b81e-506b630cd685/jobs/503
> Add CI config to schedule acceptance tests

- scripts/build.sh
| 🔗 Related issues | #163 
Using same approach as https://releases.hashicorp.com/terraform/0.14.5/
Example generated file
```
4c8fc50080f6a7d3788b5ed325c049af0b82eaecf044922307b3a68d58847210  driftctl_darwin_amd64
e6f040762e668031715282330caed723c95e82cbf510829d6d36d5324f1a6a20  driftctl_linux_386
b5a9a6bd87a31de71458f26a7718d01e93b004753e80c23cecee848172f3f056  driftctl_linux_amd64
850115affff59488868fc81db1903e226e438529f513e5a6b984f9e15bf7f180  driftctl_linux_arm
bde287b1c19f971bcc3462936e8bf4377817efd211952f759411c14266cc1972  driftctl_linux_arm64
8de8ff1398a64e2eb102c526893ed5149913e9cf9960b21da34858c29b8d6c7b …
```
> Add build checksums

- .all-contributorsrc
- CONTRIBUTORS.md
- README.md
All-Contributors specification to thank all the people who have contributed to drifctl !
You can find the usage of the bot [here](https://allcontributors.org/docs/en/bot/usage)
> Add all-contributors specification

- pkg/cmd/driftctl.go
| 🔗 Related issues | #191 
Before
After
> Make sentry attach stack for every report

- README.md
| 🔗 Related issues | #217 
Add MacPorts installation guide. Huge thanks to our awesome contributor @herbygillot
> Add MacPorts installation

- pkg/resource/aws/aws_sns_topic.go
- pkg/resource/aws/aws_sns_topic_policy.go
- pkg/resource/aws/aws_sqs_queue_policy.go
> Fix policy diff displayed inline

- README.md
Out of the box documentation for checking the binary releases missed small details!
> updates to gpg doc to make it work out of the box

- doc/cmd/scan/supported_resources/aws.md
> Fix invalid AWS policy

- doc/LIMITATIONS.md
Some users reported issues with older Terraform versions (like 0.11) and Terraform AWS providers (like 2.45).
Explicitly mention it's not supported in the current tool.
> add Terraform known limitations

- pkg/resource/aws/aws_sns_topic_policy_test.go
- pkg/resource/aws/aws_sns_topic_subscription_test.go
- pkg/resource/aws/aws_sns_topic_test.go
| ⚠ Deprecations?   |no
add polling for sns acceptency tests
> add polling for sns acc tests

- logger/config.go
- logger/logger.go
- logger/plugin_logger.go
- main.go
- pkg/terraform/plugin_client.go
- test/acceptance/testing.go
| 🔗 Related issues | #125 
Preview of logs outputs :
- DEBUG https://gist.github.com/eliecharra/e5486ad02643154ecb7badc87307834c
- TRACE https://gist.github.com/eliecharra/b6381072f1f0889e206112e9df85e92b
Question @wbeuil @moadibfr should we preserve provider log level when logging ?
> Better log handler for terraform providers

- .circleci/config.yml
- Makefile
> Allow to run acceptance tests in parallel

- .circleci/config.yml
| ❓ Documentation  | none
Only notify on failure, and add the test suite pattern to the message
> Improve acceptance test notifications

- doc/cmd/scan/filter.md
> Add doc to filter on archived repos

- README.md
Microbadger will shutdown the 01/07/2021
> Remove docker layer badge

- pkg/output/progress.go
- pkg/output/progress_test.go
fix race condition on progress that could cause deadlock
> fix race condition on progress that could cause deadlock

- README.md
| ❓ Documentation  | no  no
Asking for users feedback on README
> Asking for users feedback on README

- pkg/remote/aws/init_test.go
Fixes failure when updating golden files
> Fix missing mock on golden file update

- pkg/analyser/analyzer.go
| 🔗 Related issues | https://github.com/cloudskiff/driftctl/issues/370
> Fix broken link in unmanaged security groups

- pkg/driftctl.go
- pkg/middlewares/aws_default_route_table_test.go
- pkg/middlewares/aws_iam_policy_attachment_defaults.go
- pkg/middlewares/aws_iam_policy_attachment_defaults_test.go
Add aws_iam_role_policy_attachment to this branch.
> Strict mode lotoussa

- pkg/cmd/driftctl.go
| 🔗 Related issues | #367 
Fix typo in the #381 PR.
> Fix Typo Issue 367 error reporting

- pkg/middlewares/aws_default_igw_route.go
- pkg/middlewares/aws_default_igw_route_test.go
> Fix bug in default igw route middleware

- main.go
- pkg/cmd/scan.go
- pkg/cmd/scan_test.go
- pkg/output/progress.go
- pkg/output/progress_test.go
Add missing commits to v0.8 branch.
3 commits are from the following PRs which got merged into main by mistake: https://github.com/cloudskiff/driftctl/pull/452 https://github.com/cloudskiff/driftctl/pull/449 https://github.com/cloudskiff/driftctl/pull/448
Commits : 
- https://github.com/cloudskiff/driftctl/pull/452/commits/04f0efa7097cc808600d7d25a56763a4a62e01ab
- https://github.com/cloudskiff/driftctl/pull/448/commits/b38063da8db41af465e5246f2ff5c95ca582905c
- https://github.com/cloudskiff/driftctl/pull/448/commits/b38063da8db41af465e5246f2ff5c95ca582905c
> Cherry-pick missing changes to v0.8

- scripts/build.sh
> Fix build script broken on gox install

- pkg/driftctl_test.go
- pkg/middlewares/aws_instance_block_device.go
- pkg/middlewares/aws_instance_block_device_test.go
- pkg/resource/aws/aws_instance_test.go
| ❓ Documentation  | none
Needed to change the signature of rootDevice and blockDevice.
> Fix signature of attributes

- pkg/middlewares/aws_sqs_queue_policy_expander.go
- pkg/resource/aws/aws_sqs_queue_policy_test.go
- pkg/resource/aws/aws_sqs_queue_test.go
| 🔗 Related issues | #
fix sqs error introduced by migration to new arch
> fix sqs error introduced by migration to new arch

- pkg/remote/aws/repository/ec2_repository.go
- pkg/remote/aws/repository/ec2_repository_test.go
- pkg/remote/aws/repository/mock_EC2Repository.go
- pkg/remote/aws/subnet_supplier.go
- pkg/remote/aws/subnet_supplier_test.go
Add subnet_gateway_supplier to ec2_repository to avoid possible hidden dependency.
> Issue 165: Add subnet_supplier to ec2_repository

- pkg/middlewares/aws_sqs_queue_policy_expander.go
| ⚠ Deprecations?   |no
| 🔗 Related issues |
| ❓ Documentation  |  no 
fix policy not deleted when empty
> fix policy not deleted when empty

- pkg/resource/aws/testdata/acc/aws_vpc/terraform.tf
try to change region in vpc acc test to mitigate max number of vpc
> try to change region in vpc acc test to mitigate max number of vpc

- pkg/remote/aws/repository/ec2_repository.go
- pkg/remote/aws/repository/ec2_repository_test.go
- pkg/remote/aws/repository/mock_EC2Repository.go
- pkg/remote/aws/route_supplier.go
- pkg/remote/aws/route_supplier_test.go
Add route_supplier to ec2_repository to avoid possible hidden dependency.
> Add route_supplier to ec2_repository

- pkg/resource/aws/testdata/acc/aws_vpc/terraform.tf
Reverts cloudskiff/driftctl#531
> Revert "try to change region in vpc acc test to mitigate max number of vpc"

- pkg/remote/aws/repository/ec2_repository.go
- pkg/remote/aws/repository/ec2_repository_test.go
- pkg/remote/aws/repository/mock_EC2Repository.go
- pkg/remote/aws/vpc_security_group_rule_supplier.go
- pkg/remote/aws/vpc_security_group_rule_supplier_test.go
- pkg/remote/aws/vpc_security_group_supplier.go
- pkg/remote/aws/vpc_security_group_supplier_test.go
Add vpc_security_group/_rule_supplier to ec2_repository to avoid possible hidden dependency.
> Add vpc_security_group/_rule to ec2_repository

- pkg/resource/aws/testdata/acc/aws_db_subnet_group/terraform.tf
- pkg/resource/aws/testdata/acc/aws_eip/terraform.tf
- pkg/resource/aws/testdata/acc/aws_subnet/terraform.tf
- pkg/resource/aws/testdata/acc/aws_vpc/terraform.tf
- test/acceptance/testing.go
run tf destroy event when apply fail during acc test
also added some name on vpc and subnet that collided so we can check which test leak...
> run tf destroy event when apply fail during acc test

- pkg/resource/aws/aws_db_instance.go
- pkg/resource/aws/aws_iam_access_key.go
- pkg/resource/aws/aws_iam_access_key_test.go
- pkg/resource/aws/aws_security_group_rule_test.go
- pkg/resource/aws/testdata/acc/aws_iam_access_key/terraform.tf
- pkg/resource/aws/testdata/acc/aws_security_group/terraform.tf
- pkg/resource/aws/testdata/acc/aws_security_group_rule/.terraform.lock.hcl
- pkg/resource/aws/testdata/acc/aws_security_group_rule/terraform.tf
> Fix db iam sg false positive

- .circleci/config.yml
- scripts/halt_before_acc.sh
| 🔗 Related issues | #541 
Allow to run acceptence tests on ci by adding [RUN ACC] tag to a commit
> add tag to be able to run acc test on pr

- pkg/iac/terraform/state/terraform_state_reader.go
- pkg/resource/resource_types.go
> Fix unsupported resources read from state files

- pkg/remote/aws/repository/ec2_repository.go
- pkg/remote/aws/repository/ec2_repository_test.go
This PR improves the unit tests for EC2 repository cache.
> Improve testing for EC2 repository cache

- pkg/cmd/gen_driftignore.go
Fixes #590
Hi @wbeuil, how does this look?
Let me know if this needs any changes.
Thanks
> Fix gen-driftignore --help example

- pkg/cmd/scan.go
- pkg/cmd/scan_test.go
- pkg/driftctl.go
- pkg/iac/terraform/state/terraform_state_reader_test.go
- pkg/remote/aws/init.go
- pkg/remote/aws/init_test.go
- pkg/remote/aws/provider.go
- pkg/remote/github/init.go
- pkg/remote/github/init_test.go
- pkg/remote/github/provider.go
- pkg/remote/remote.go
- pkg/terraform/error/provider_download_error.go
- pkg/terraform/provider_config.go
- pkg/terraform/provider_config_test.go
- pkg/terraform/provider_downloader.go
- pkg/terraform/provider_downloader_test.go
- pkg/terraform/provider_installer.go
- pkg/terraform/provider_installer_test.go
| 🔗 Related issues | #347 #570 
| ❓ Documentation  | yes https://github.com/cloudskiff/driftctl-docs/pull/67
> Allow to specify a terraform provider version

- pkg/remote/aws/sns_topic_subscription_supplier.go
- pkg/remote/aws/sns_topic_subscription_supplier_test.go
| 🔗 Related issues | #601 
backport fix to #601 in 0.9
> backport fix to #601 in 0.9

- Makefile
- pkg/resource/aws/aws_iam_access_key_test.go
- pkg/resource/aws/testdata/acc/aws_dynamodb_table/main.tf
- pkg/resource/aws/testdata/acc/aws_eip/terraform.tf
- pkg/resource/aws/testdata/acc/aws_internet_gateway/terraform.tf
- pkg/resource/aws/testdata/acc/aws_route/.terraform.lock.hcl
- pkg/resource/aws/testdata/acc/aws_route/terraform.tf
- pkg/resource/aws/testdata/acc/aws_route_table/terraform.tf
- pkg/resource/aws/testdata/acc/aws_route_table_association/terraform.tf
- pkg/resource/aws/testdata/acc/aws_security_group/terraform.tf
- pkg/resource/aws/testdata/acc/aws_security_group_rule/terraform.tf
- pkg/resource/aws/testdata/acc/aws_subnet/terraform.tf
- pkg/resource/aws/testdata/acc/aws_vpc/terraform.tf
- test/result.go
fix iam_access_key acceptance test
> fix iam_access_key acceptance test

- pkg/remote/aws/init.go
- pkg/remote/aws/kms_alias_supplier_test.go
- pkg/remote/aws/kms_key_supplier_test.go
- pkg/remote/aws/repository/kms_repository.go
- pkg/remote/aws/repository/kms_repository_test.go
This PR implements cache in the AWS KMS repository.
> Implement cache in AWS KMS repository

- pkg/remote/aws/ecr_repository_supplier_test.go
- pkg/remote/aws/init.go
- pkg/remote/aws/repository/ecr_repository.go
- pkg/remote/aws/repository/ecr_repository_test.go
This PR implements cache in the AWS ECR repository.
> Implement cache in AWS ECR repository

- pkg/remote/aws/dynamodb_table_supplier_test.go
- pkg/remote/aws/init.go
- pkg/remote/aws/repository/dynamodb_repository.go
- pkg/remote/aws/repository/dynamodb_repository_test.go
This PR implements cache in the AWS DynamoDB repository.
> Implement cache in AWS DynamoDB repository

- pkg/remote/aws/cloudfront_distribution_supplier_test.go
- pkg/remote/aws/init.go
- pkg/remote/aws/repository/cloudfront_repository.go
- pkg/remote/aws/repository/cloudfront_repository_test.go
This PR implements cache in the AWS Cloudfront repository.
> Implement cache in AWS cloudfront repository

- pkg/remote/github/init.go
- pkg/remote/github/repository.go
- pkg/remote/github/repository_test.go
This PR implements cache in the Github repository.
> Implement cache in Github repository

- pkg/cmd/scan/output/assets/index.tmpl
- pkg/cmd/scan/output/assets/style.css
- pkg/cmd/scan/output/testdata/output.html
- pkg/cmd/scan/output/testdata/output_empty.html
- pkg/cmd/scan/output/testdata/output_sync.html
@sundowndev this one is for you.
Made the html more responsive and with a focus on a11y.
> Refactor output HTML with a11y and responsive in mind

- pkg/resource/aws/aws_ebs_volume.go
- pkg/resource/aws/aws_instance_test.go
- pkg/resource/aws/testdata/acc/aws_instance_default/.terraform.lock.hcl
- pkg/resource/aws/testdata/acc/aws_instance_default/terraform.tf
> Fix EBS volume drift on throughput

- pkg/resource/aws/aws_route.go
| 🔗 Related issues | #630 
Fix aws_route false positive
> Fix aws_route carrier_gateway_id false positive

- pkg/resource/aws/aws_sns_topic.go
- pkg/resource/aws/aws_sns_topic_policy.go
| 🔗 Related issues | #637 
Fix false positive declared in issue + another false positive for topic and topic policy
> aws sns topic/policy fix false positive

- Makefile
- pkg/driftctl.go
- pkg/driftctl_test.go
- pkg/middlewares/aws_defaults.go
- pkg/middlewares/aws_role_managed_policy_expander.go
- pkg/resource/aws/aws_iam_role_test.go
- pkg/resource/aws/testdata/acc/aws_iam_role/.terraform.lock.hcl
- pkg/resource/aws/testdata/acc/aws_iam_role/terraform.tf
- pkg/resource/aws/testdata/acc/aws_iam_role_with_managed_policies/.terraform.lock.hcl
- pkg/resource/aws/testdata/acc/aws_iam_role_with_managed_policies/terraform.tf
> Handle managed_policy_arns in aws_iam_roles

- pkg/middlewares/aws_instance_block_device.go
- pkg/middlewares/aws_instance_block_device_test.go
> Add missing attribute to volume expander middleware

- pkg/middlewares/aws_instance_block_device.go
- pkg/middlewares/aws_instance_block_device_test.go
| 🔗 Related issues | #564
Fix false positive for ebs volume tags
> Fix ebs volume tags false positive

- pkg/analyser/analyzer.go
- pkg/cmd/scan/output/testdata/output_computed_fields.json
- pkg/cmd/scan/output/testdata/output_computed_fields.txt
Add link to limitations for computed field alert
> Add limitation link in computed field alert

- pkg/iac/terraform/state/enumerator/glob.go
- pkg/iac/terraform/state/enumerator/s3.go
- pkg/iac/terraform/state/enumerator/s3_test.go
| 🔗 Related issues | #695 
Change S3 prefix and pattern split logic
> Fix S3 broken glob matching

- pkg/output/progress.go
| 🔗 Related issues | #703 
Inverse scan spinner rotation
> Inverse scan spinner rotation

- pkg/cmd/driftctl_test.go
- pkg/cmd/scan.go
- pkg/cmd/scan/output/output.go
- pkg/cmd/scan/output/output_test.go
- pkg/cmd/scan/output/plan.go
- pkg/cmd/scan/output/plan_test.go
- pkg/cmd/scan/output/testdata/output_plan.json
- pkg/cmd/scan/output/testdata/output_plan_empty.json
- pkg/cmd/scan_test.go
> First iteration of the output plan

- pkg/driftctl.go
- pkg/driftctl_test.go
- pkg/middlewares/aws_eip_association_expander.go
- pkg/resource/aws/aws_eip_association_test.go
- pkg/resource/aws/testdata/acc/aws_eip_association/.terraform.lock.hcl
- pkg/resource/aws/testdata/acc/aws_eip_association/mainf.tf
| 🔗 Related issues | #563 
add middleware to expand eip association embedded inside eip
> add middleware to expand eip association embedded inside eip

- pkg/remote/aws/repository/kms_repository.go
- pkg/remote/aws/repository/kms_repository_test.go
- pkg/remote/common/details_fetcher.go
> Fix kms_key crash

- pkg/remote/aws/ec2_route_details_fetcher.go
Fix acceptance tests https://circleci.com/gh/cloudskiff/driftctl/5003
> Fix ipv6 route detail retrieval

- pkg/remote/aws/init.go
The acc tests were failing while reading sgrule resources https://app.circleci.com/pipelines/github/cloudskiff/driftctl/2568/workflows/8bdb71f6-0f0f-45b3-a78b-b56925efdec6/jobs/5056/tests#failed-test-1
> Use security group rule details fetcher

- pkg/remote/aws/route53_record_enumerator.go
| 🔗 Related issues | Fix #845 
> Add type to `route53_records` in enumerator

- pkg/cmd/scan/output/assets/index.tmpl
- pkg/cmd/scan/output/testdata/output.html
- pkg/cmd/scan/output/testdata/output_empty.html
| 🔗 Related issues | #693 
The search bar now search resource IDs and resource types with clearer wording
> Clarify HTML report input wording

- pkg/remote/aws/ec2_route_enumerator.go
- pkg/remote/ec2_scanner_test.go
| 🔗 Related issues | Fix #843 
> Add origin to `aws_route` in enumerator

- pkg/cmd/scan/output/html.go
- pkg/cmd/scan/output/testdata/output.html
| 🔗 Related issues | #808
Before
After
> Fix rounding issue in html output

- pkg/remote/aws/ec2_internet_gateway_enumerator.go
- pkg/remote/aws/ec2_route_enumerator.go
| 🔗 Related issues | Fix #844
enrich internet gateway and route to use in default igw route middleware
> enrich internet gateway and route to use in default igw route middleware

- pkg/remote/aws/repository/ec2_repository.go
- pkg/remote/aws/repository/ec2_repository_test.go
> Ignore terminated instance from enumeration

- pkg/resource/aws/aws_instance.go
- pkg/resource/aws/aws_route53_health_check.go
> Fix tag Name not displayed in deep mode

- pkg/cmd/scan/output/console.go
- pkg/cmd/scan/output/html_test.go
- pkg/cmd/scan/output/output_test.go
- pkg/cmd/scan/output/testdata/output.txt
- pkg/cmd/scan/output/testdata/output_computed_fields.txt
- pkg/cmd/scan/output/testdata/output_json_fields.txt
- pkg/cmd/scan/output/testdata/output_stringer_resources.txt
- pkg/resource/resource.go
> Group changes by IaC source in console output

- scripts/build.sh
> Publish release when CI env var is set to true 

- pkg/remote/cloudfront_scanner_test.go
- pkg/remote/dynamodb_scanner_test.go
- pkg/remote/ec2_scanner_test.go
- pkg/remote/ecr_scanner_test.go
- pkg/remote/github_branch_protection_scanner_test.go
- pkg/remote/github_membership_scanner_test.go
- pkg/remote/github_repository_scanner_test.go
- pkg/remote/github_team_membership_scanner_test.go
- pkg/remote/github_team_scanner_test.go
- pkg/remote/iam_scanner_test.go
- pkg/remote/kms_scanner_test.go
- pkg/remote/lambda_scanner_test.go
- pkg/remote/rds_scanner_test.go
- pkg/remote/route53_scanner_test.go
- pkg/remote/s3_scanner_test.go
- pkg/remote/sns_scanner_test.go
- pkg/remote/sqs_scanner_test.go
> Improve assertions on alerter mock in tests

- pkg/cmd/scan/output/assets/index.tmpl
- pkg/cmd/scan/output/html.go
- pkg/cmd/scan/output/html_test.go
- pkg/cmd/scan/output/testdata/output_coverage_100.html
> Display drifts in HTML output even when coverage is 100%

- pkg/cmd/scan/output/output_test.go
- pkg/cmd/scan/output/testdata/output.html
- pkg/cmd/scan/output/testdata/output_access_denied_alert_aws.json
- pkg/cmd/scan/output/testdata/output_access_denied_alert_aws.txt
- pkg/cmd/scan/output/testdata/output_access_denied_alert_github.json
- pkg/cmd/scan/output/testdata/output_access_denied_alert_github.txt
- pkg/remote/alerts/alerts.go
- pkg/remote/cloudfront_scanner_test.go
- pkg/remote/dynamodb_scanner_test.go
- pkg/remote/ec2_scanner_test.go
- pkg/remote/ecr_scanner_test.go
- pkg/remote/github_branch_protection_scanner_test.go
- pkg/remote/github_membership_scanner_test.go
- pkg/remote/github_repository_scanner_test.go
- pkg/remote/github_team_membership_scanner_test.go
- pkg/remote/github_team_scanner_test.go
- pkg/remote/google_storage_scanner_test.go
- pkg/remote/iam_scanner_test.go
- pkg/remote/kms_scanner_test.go
- pkg/remote/lambda_scanner_test.go
- pkg/remote/rds_scanner_test.go
- pkg/remote/resource_enumeration_error_handler_test.go
- pkg/remote/route53_scanner_test.go
- pkg/remote/s3_scanner_test.go
- pkg/remote/sns_scanner_test.go
- pkg/remote/sqs_scanner_test.go
> Add original error message for scan errors

- docs/testing.md
Document how to mock a repository
| 🔗 Related issues | Fix #949
This PR adds docs about mocking a repository.
> Document how to mock repositories

- pkg/remote/azurerm/repository/storage.go
- pkg/remote/azurerm/repository/storage_test.go
When an error occur while retrieving result, we were hiding it ...
> Fix azure may hide some errors

- docs/middlewares.md
| 🔗 Related issues | Fix #950
This PR adds docs about middlewares: what middlewares does and how to create one.
> Add docs about middlewares

- docs/testing.md
> Update testing example

- pkg/iac/terraform/state/terraform_state_reader_test.go
- pkg/iac/terraform/state/test/google_compute_router/results.golden.json
- pkg/iac/terraform/state/test/google_compute_router/terraform.tfstate
- pkg/remote/google/google_compute_firewall_enumerator.go
- pkg/remote/google/google_compute_router_enumerator.go
- pkg/remote/google/init.go
- pkg/remote/google/repository/asset.go
- pkg/remote/google/util.go
- pkg/remote/google_compute_scanner_test.go
- pkg/resource/google/google_compute_router.go
- pkg/resource/google/google_compute_router_test.go
- pkg/resource/google/metadatas.go
- pkg/resource/google/testdata/acc/google_compute_router/.terraform.lock.hcl
- pkg/resource/google/testdata/acc/google_compute_router/terraform.tf
- pkg/resource/resource_types.go
| 🔗 Related issues | #1004 
| ❓ Documentation  | https://github.com/cloudskiff/driftctl-docs/pull/122
> Add google_compute_router

- pkg/iac/terraform/state/terraform_state_reader_test.go
- pkg/iac/terraform/state/test/google_compute_instance/results.golden.json
- pkg/iac/terraform/state/test/google_compute_instance/terraform.tfstate
- pkg/remote/google/google_compute_instance_enumerator.go
- pkg/remote/google/init.go
- pkg/remote/google/repository/asset.go
- pkg/remote/google_compute_scanner_test.go
- pkg/resource/google/google_compute_instance.go
- pkg/resource/google/google_compute_instance_test.go
- pkg/resource/google/testdata/acc/google_compute_instance/.terraform.lock.hcl
- pkg/resource/google/testdata/acc/google_compute_instance/terraform.tf
- pkg/resource/resource_types.go
| 🔗 Related issues | #1000 
| ❓ Documentation  | https://github.com/cloudskiff/driftctl-docs/pull/113
> Add google_compute_instance

- .circleci/config.yml
This move our acc test to a new dedicated azure subscription
> Remove skip subscription for azure

- pkg/iac/terraform/state/terraform_state_reader_test.go
- pkg/iac/terraform/state/test/api_gateway_account/results.golden.json
- pkg/iac/terraform/state/test/api_gateway_account/terraform.tfstate
- pkg/remote/api_gateway_scanner_test.go
- pkg/remote/aws/api_gateway_account_enumerator.go
- pkg/remote/aws/init.go
- pkg/remote/aws/repository/api_gateway_repository.go
- pkg/remote/aws/repository/api_gateway_repository_test.go
- pkg/remote/aws/repository/mock_ApiGatewayRepository.go
- pkg/resource/aws/aws_api_gateway_account.go
- pkg/resource/aws/aws_api_gateway_account_test.go
- pkg/resource/aws/testdata/acc/aws_api_gateway_account/.terraform.lock.hcl
- pkg/resource/aws/testdata/acc/aws_api_gateway_account/terraform.tf
- pkg/resource/resource_types.go
| 🔗 Related issues | #960
Add aws_api_gateway_account resource
> Add api_gateway_account

- pkg/remote/azurerm/init.go
> Fix crash when no lockfile are found (Azure)

- go.mod
- pkg/middlewares/aws_api_gateway_rest_api_expander.go
- pkg/middlewares/aws_api_gateway_rest_api_expander_test.go
| ❌ BC Break       | yes/no
| 🔗 Related issues | #1203
Cherry pick #1204 in branch `v0.16`
> Hotfix #1203

- pkg/iac/terraform/state/terraform_state_reader_test.go
- pkg/iac/terraform/state/test/google_cloudrun_service/results.golden.json
- pkg/iac/terraform/state/test/google_cloudrun_service/terraform.tfstate
- pkg/remote/google/google_cloudrun_service_enumerator.go
- pkg/remote/google/init.go
- pkg/remote/google/repository/asset.go
- pkg/remote/google/repository/mock_AssetRepository.go
- pkg/remote/google_cloudrun_scanner_test.go
- pkg/resource/google/google_cloudrun_service.go
- pkg/resource/google/google_cloudrun_service_test.go
- pkg/resource/google/metadata_test.go
- pkg/resource/google/testdata/acc/google_cloudrun_service/.driftignore
- pkg/resource/google/testdata/acc/google_cloudrun_service/.terraform.lock.hcl
- pkg/resource/google/testdata/acc/google_cloudrun_service/terraform.tf
- pkg/resource/resource_types.go
| 🔗 Related issues | #983 
| ❓ Documentation  | https://github.com/cloudskiff/driftctl-docs/pull/177
> Add google_cloudrun_service

- pkg/iac/terraform/state/terraform_state_reader_test.go
- pkg/iac/terraform/state/test/api_gateway_integration_response/results.golden.json
- pkg/iac/terraform/state/test/api_gateway_integration_response/terraform.tfstate
- pkg/middlewares/aws_api_gateway_rest_api_expander.go
- pkg/middlewares/aws_api_gateway_rest_api_expander_test.go
- pkg/remote/aws/api_gateway_integration_response_enumerator.go
- pkg/remote/aws/init.go
- pkg/remote/aws_api_gateway_scanner_test.go
- pkg/resource/aws/aws_api_gateway_integration_response.go
- pkg/resource/aws/aws_api_gateway_integration_response_test.go
- pkg/resource/aws/metadata_test.go
- pkg/resource/aws/testdata/acc/aws_api_gateway_integration_response/.driftignore
- pkg/resource/aws/testdata/acc/aws_api_gateway_integration_response/.terraform.lock.hcl
- pkg/resource/aws/testdata/acc/aws_api_gateway_integration_response/terraform.tf
- pkg/resource/resource_types.go
| 🔗 Related issues | #1199 
| ❓ Documentation  | https://github.com/cloudskiff/driftctl-docs/pull/179
> Add aws_api_gateway_integration_response resource

- README.md
> Add 🇮🇱  flag

- pkg/iac/terraform/state/terraform_state_reader_test.go
- pkg/iac/terraform/state/test/google_compute_node_group/results.golden.json
- pkg/iac/terraform/state/test/google_compute_node_group/terraform.tfstate
- pkg/remote/google/google_compute_node_group_enumerator.go
- pkg/remote/google/init.go
- pkg/remote/google/repository/asset.go
- pkg/remote/google/repository/mock_AssetRepository.go
- pkg/remote/google_compute_scanner_test.go
- pkg/resource/google/google_compute_node_group.go
- pkg/resource/google/google_compute_node_group_test.go
- pkg/resource/google/metadata_test.go
- pkg/resource/google/testdata/acc/google_compute_node_group/.driftignore
- pkg/resource/google/testdata/acc/google_compute_node_group/terraform.tf
- pkg/resource/resource_types.go
| 🔗 Related issues | #1002 
add support for google_compute_node_group
> add support for google_compute_node_group

- .goreleaser.yml
This adds artifact to the release bundle with acknowledgments of all dependencies for licensing purposes.
> chore: add licensing acknowledgments

- pkg/iac/terraform/state/backend/gs_reader_test.go
- pkg/iac/terraform/state/backend/testdata/gcp_application_default_credentials.json
> Avoid triggering auth in GCS backend tests

- README.md
This repo contains many tfstate files for testing purposes. Resource
names and other values in here are just opaque strings, and no running
code attempts to access such resources.
Documenting this might prevent bug bounty hunters from filing security
reports about things like unclaimed S3 bucket names.
> Document meaninglessness of test tfstate values

- pkg/resource/google/google_bigquery_dataset_test.go
Add retry policy to the acceptance test for google_bigquery_dataset resource.
> Add retry policy for google_bigquery_dataset acc test

- .snyk
Ignore vuln in terraform dependency
> Ignore vuln in terraform dependencies

- scripts/changelog.sh
This PR fixes shellscript issues found in the changelog script.
> Fix shellcheck issues in changelog script

- pkg/resource/aws/aws_dynamodb_table_test.go
- pkg/resource/aws/aws_ecr_repository_test.go
- pkg/resource/aws/aws_eip_test.go
- pkg/resource/aws/aws_iam_policy_attachment_test.go
- pkg/resource/aws/aws_instance_test.go
- pkg/resource/aws/aws_internet_gateway_test.go
- pkg/resource/aws/aws_lambda_event_source_mapping_test.go
- pkg/resource/aws/aws_launch_configuration_test.go
- pkg/resource/aws/aws_launch_template_test.go
- pkg/resource/aws/aws_nat_gateway_test.go
- pkg/resource/aws/aws_network_acl_test.go
- pkg/resource/aws/aws_route53_health_check_test.go
- pkg/resource/aws/aws_route53_record_test.go
- pkg/resource/aws/aws_route_table_association_test.go
- pkg/resource/aws/aws_route_table_test.go
- pkg/resource/aws/aws_route_test.go
- pkg/resource/aws/aws_s3_bucket_test.go
- pkg/resource/aws/aws_security_group_test.go
- pkg/resource/aws/aws_sns_topic_policy_test.go
- pkg/resource/aws/aws_sns_topic_subscription_test.go
- pkg/resource/aws/aws_sns_topic_test.go
- pkg/resource/aws/aws_sqs_queue_policy_test.go
- pkg/resource/aws/aws_sqs_queue_test.go
- pkg/resource/aws/aws_subnet_test.go
- pkg/resource/aws/aws_vpc_test.go
- renamed TestAcc_Aws* to TestAcc_Aws_*
- added missing AWS_REGION env to AWS acc tests
- added retries on flaky acc tests
> AWS acceptance tests

- pkg/iac/terraform/state/enumerator/azurerm.go
- pkg/iac/terraform/state/terraform_state_reader_acc_test.go
- pkg/iac/terraform/state/terraform_state_reader_azure_acc_test.go
- pkg/iac/terraform/state/testdata/acc/multiple_states/route53/terraform.tf
- pkg/iac/terraform/state/testdata/acc/multiple_states/s3/terraform.tf
- test/acceptance/testing.go
Fix acceptance test on state reader
> chore: fix failed ACC tests

- scripts/issue-tagging.sh
This PR fixes the issue tagging script. This script is intended to make users notice that a new release is available with a new patch or feature, as well as grouping tickets in milestones automatically. This script was tested locally and works as expected.
Note it passed all tests with shellcheck.
**fix: issue tagging script**
This commit fixes the grep expression that parses the related issue ID on pull requests. It is intended to ignore pull requests that don't mention any issue as well. The `|| true` forces exit code 0 when grep has no match, for some reason the `-q` option would not achieve this. It also fixes the milestone API endpoint missing a 's'. Finally, it uses $LATEST_TAG instead of  $BASE_TAG variable as the new version.
> Fix issue tagging script

- scripts/changelog.sh
| ❓ Documentation  | internal maintainer docs - maybe
**chore: include uncategorised changes in changelog**
Ensure all PRs, even ones missing a "kind" label, are present in the
generated changelog. During the manually-initiated release process,
maintainers can edit the changelog to categorise them if they wish.
If we move to an automated, continuous release, it will still be better
to include uncategorised PRs than to omit them altogether.
I can't find any maintainer docs around the manually-initiated parts of our release process, do we have any? ~~Either way, this PR as it stands now would require us to manually …
> chore: include uncategorised changes in changelog

- pkg/remote/aws/apigatewayv2_mapping_enumerator.go
- pkg/remote/aws_apigatewayv2_scanner_test.go
- pkg/resource/aws/aws_apigatewayv2_mapping.go
This PR cherry-pick #1380 into v0.23 branch.
> Cherry-pick: fix: panic in apigatewayv2_api_mapping enumerator

- pkg/iac/terraform/state/terraform_state_reader_acc_test.go
- pkg/resource/aws/aws_cloudfront_distribution_test.go
- pkg/resource/aws/aws_network_acl_test.go
- pkg/resource/aws/aws_route_table_test.go
- pkg/resource/aws/aws_s3_bucket_public_access_block_test.go
- pkg/resource/aws/aws_sqs_queue_test.go
- pkg/resource/aws/aws_vpc_test.go
- pkg/resource/google/google_compute_subnetwork_test.go
- pkg/resource/google/google_dns_managed_zone_test.go
- pkg/resource/google/google_storage_bucket_iam_binding_test.go
- pkg/resource/google/google_storage_bucket_iam_member_test.go
- pkg/resource/google/google_storage_bucket_test.go
This PR skips the tests that have been flaky for the past weeks.
> fix: skip flaky tests

- .editorconfig
- pkg/resource/azurerm/azurerm_lb_rule_test.go
> feat: skip flaky tests

- .circleci/config.yml
- go.mod
- go.sum
> feat: add security quality gates
