pkg/resource/aws/testdata/acc/aws_instance/providers.tf
test/acceptance/testing.go

- Better terraform error output
- Remove terraform version constraint in test files
Fix acceptance test not running since we upgraded terraform version.
Also add a better output for terraform related command errors

Fix acceptance tests

---

pkg/driftctl.go
pkg/middlewares/aws_instance_eip.go
pkg/middlewares/aws_instance_eip_test.go

Handle aws EIP false positive on instance, mitigates #11

Avoid to display false positive drift on instances when eip attached

---

.dockerignore
Dockerfile
README.md
scripts/build.sh

Added docker file  to build drifctl docker image.
Documentation to run driftctl from docker

add a docker for drifctl

---

doc/README.md
pkg/cmd/driftctl.go
pkg/cmd/driftctl_test.go

Allow to use env to disable version check

Add env to disable version check

---

README.md

| 🔗 Related issues | #41 
Documentation wasn't standard enough for some use cases. 
Those updates worked on my fedora env, my ubuntu docker env, and validated on Windows 10

updated doc following user feedback 

---

README.md
doc/cmd/scan/supported_resources/aws.md

| 🔗 Related issues | #46
It is possible to use driftctl with IAM role by defining a named profile.
As per [AWS documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html) an example could be:
```bash
[profile marketingadmin]
role_arn = arn:aws:iam::123456789012:role/marketingadminrole
source_profile = user1
region = eu-west-3 # to avoid overriding AWS_REGION setting
```
And then:
```bash
$ AWS_PROFILE=marketingadmin driftctl scan
```

Add documentation about AWS authentication

---

pkg/analyser/analyzer_test.go
pkg/cmd/scan/output/output_test.go
pkg/filter/driftignore_test.go

| 🔗 Related issues | #37 
Change each resource that was added to `[]resource.Resource` as a pointer to `FakeResource` to be consistent with what we have in production.

Consistency across resources

---

.circleci/config.yml
pkg/middlewares/aws_instance_eip.go
pkg/middlewares/aws_instance_eip_test.go

| 🔗 Related issues |
We had badly formated (not passed to fmt) file in main. `make` will create diff that add noise to PR.
I added a check on ci during tests phase to prevent PR to be merge when fmt is not ok.

add fmt check in ci

---

Dockerfile
README.md

| ❌ BC Break       | yes
| 🔗 Related issues | #47 
Adds $HOME support to split code/state and home concerns in docker image (+updated documentation)

add home support for docker image

---

pkg/terraform/provider_installer_test.go

| 🔗 Related issues | #60 
Fix hardcoded linux_amd64 hardcoded values in test expectations

Fix test execution failed on darwin

---

pkg/iac/terraform/state/terraform_state_reader.go
pkg/iac/terraform/state/terraform_state_reader_test.go
pkg/iac/terraform/state/test/unsupported_attribute/result.golden.json
pkg/iac/terraform/state/test/unsupported_attribute/terraform.tfstate

| 🔗 Related issues | #59 
This PR allow us to ignore new fields from a state generated from a newer version of terraform provider.
It allow us to read state coming from aws provider version 3.22 if we currently only support version 3.19.
This PR also changes error mgmt during state reading, if we cannot decode a part of the state, we stop execution. It prevent us to return inconsistent drift result as some resources from the state are missing.
- https://github.com/zclconf/go-cty/issues/60

Ignore unknown attributes error in state

---

pkg/resource/aws/aws_instance_test.go
pkg/resource/aws/testdata/acc/aws_instance/.terraform.lock.hcl
pkg/resource/aws/testdata/acc/aws_route53_record/.terraform.lock.hcl
test/acceptance/testing.go

- Add filter on aws_instance test
- Add terraform locks
- Do not run terraform init if already done previously
- Do not use chdir in tests (it could cause race if we want to switch to parallel tests, uses --from arg instead)
- Handle terraform destroy errors

Several improvements on acceptance tests

---

pkg/remote/aws/s3_bucket_supplier.go
pkg/resource/aws/aws_s3_bucket_test.go
pkg/resource/aws/testdata/acc/aws_s3_bucket/.terraform.lock.hcl
pkg/resource/aws/testdata/acc/aws_s3_bucket/providers.tf
pkg/resource/aws/testdata/acc/aws_s3_bucket/s3.tf

| 🔗 Related issues | #73 
According to AWS SDK documentation, buckets in `us-east-1` region return `nil` in `GetBucketLocation`

Fix crash for buckets in us-east-1

---

pkg/driftctl.go

| 🔗 Related issues | #86 
Ensure IaC source are valid prevent us to fail after a potentially long
running cloud resources scan.

Start by reading IaC before enumerate cloud resources

---

doc/contributing/tests.md
pkg/alerter/alert.go
pkg/alerter/alerter.go
pkg/alerter/alerter_test.go
pkg/analyser/analysis.go
pkg/analyser/analyzer.go
pkg/analyser/analyzer_test.go
pkg/analyser/testdata/input.json
pkg/analyser/testdata/output.json
pkg/cmd/scan.go
pkg/cmd/scan/output/console.go
pkg/cmd/scan/output/console_test.go
pkg/cmd/scan/output/json_test.go
pkg/cmd/scan/output/output_test.go
pkg/cmd/scan/output/testdata/output.json
pkg/cmd/scan/output/testdata/output_computed_fields.json
pkg/cmd/scan/output/testdata/output_computed_fields.txt
pkg/driftctl.go
pkg/remote/aws/init.go
pkg/remote/remote.go
pkg/resource/aws/aws_instance_test.go
pkg/scanner.go
test/acceptance/result.go
test/resource/resource.go

| 🔗 Related issues | #7
Simple way to start a goroutine and to send alerts to it so as to display useful information to users.
An example could be if there are computed attributes of a resource that drifted but wasn't refreshed inside the tfstates, we should inform the user that he/she needs to refresh its states since it could be a false positive drift.

Handle alert during execution

---

doc/cmd/scan/iac_source.md

| 🔗 Related issues | #105
Just documentation update to fix the issue after testing it successfully locally.

Fix wrong documentation telling driftctl needs write access to S3 state files

---

doc/contributing/tests.md
test/acceptance/testing.go
test/acceptance/testing_test.go

Allow to override env vars for terraform operations in acc tests

---

doc/cmd/completion/script.md

current doc can't work as is
proposed fixed with sudo and tee
fixes a misleading bash documentation for linux

bash completion doc fix

---

pkg/iac/terraform/state/terraform_state_reader.go
pkg/iac/terraform/state/terraform_state_reader_test.go
pkg/iac/terraform/state/test/module.iam_iam-user/result.golden.json
pkg/iac/terraform/state/test/module.iam_iam-user/terraform.tf
pkg/iac/terraform/state/test/module.iam_iam-user/terraform.tfstate

| 🔗 Related issues | #142 
Allow to read IaC resources from modules

Add support for terraform modules

---

main.go
pkg/cmd/driftctl.go
pkg/cmd/errors/scan.go
pkg/cmd/scan.go
test/acceptance/testing.go

Return exit code 1 when infrastructure not in sync

---

pkg/driftctl.go
pkg/middlewares/aws_bucket_policy_expander.go
pkg/middlewares/aws_bucket_policy_expander_test.go

Bug found yesterday where it was possible to create an inline policy that was viewed as unmanaged.
To be coherent with what we already have for the routes and security group rules, we should explode inline poilicy from state s3_bucket resource and create s3_bucket_policy from it.

Middleware to explode inline policy

---

pkg/analyser/analyzer.go
pkg/analyser/analyzer_test.go

hotfix for multiple computed alert being send

hotfix for multiple computed alert being send

---

Makefile

As we use minimal enviroment in our CircleCI build, sometimes the linter fail with a timeout like there : https://app.circleci.com/pipelines/github/cloudskiff/driftctl/369/workflows/2d4f9c86-d119-48af-abe4-7a1e734e673f/jobs/448
This pull request increase the linter timeout to 2 minutes

Fix lint sometimes fail in CI

---

doc/cmd/scan/supported_resources/aws.md

Changed the url of the launch stack. It's now on the `quickcreate` endpoint to get up and running with our custom driftctl role faster.
Added 2 ways to update the CloudFormation template (console and aws cli)

Update CloudFormation launch stack docs

---

test/acceptance/testing.go

| 🔗 Related issues | #175
I fixed #175.
Please review my commit!

Embed the environment variables before PreExec in ACC test

---

pkg/resource/aws/aws_instance_test.go
test/acceptance/testing.go

Cobra cmd seems to return flag twice when executed multiples times.
I moved cmd creation in the loop to start with a fresh cobra cmd each time.
First check
Second check

Fix unexpected deleted resources in acceptance tests

---

pkg/resource/aws/aws_sqs_queue_policy_test.go
pkg/resource/aws/aws_sqs_queue_test.go
test/acceptance/testing.go
test/acceptance/testing_test.go

Found error in CI while running acceptance tests. The problem in short is that SQS queues has a weird behaviour where creation/deletion takes time to propagate. TLDR, we need to poll to list sqs queues in a pre check.

Add retry mechanism for polling and use it to poll sqs queues during acc tests

---

.golangci.yml
pkg/remote/aws/ec2_eip_association_supplier.go
pkg/remote/aws/iam_role_policy_supplier.go
pkg/remote/aws/vpc_security_group_rule_supplier.go
pkg/resource/aws/deserializer/db_instance_deserializer.go
pkg/resource/aws/deserializer/db_subnet_group_deserializer.go
pkg/resource/aws/deserializer/default_route_table_deserializer.go
pkg/resource/aws/deserializer/default_security_group_deserializer.go
pkg/resource/aws/deserializer/default_subnet_deserializer.go
pkg/resource/aws/deserializer/default_vpc_deserializer.go
pkg/resource/aws/deserializer/internet_gateway_deserializer.go
pkg/resource/aws/deserializer/nat_gateway_deserializer.go
pkg/resource/aws/deserializer/route53_record_deserializer.go
pkg/resource/aws/deserializer/route53_zone_deserializer.go
pkg/resource/aws/deserializer/route_deserializer.go
pkg/resource/aws/deserializer/route_table_association_deserializer.go
pkg/resource/aws/deserializer/route_table_deserializer.go
pkg/resource/aws/deserializer/sqs_queue_deserializer.go
pkg/resource/aws/deserializer/sqs_queue_policy_deserializer.go
pkg/resource/aws/deserializer/subnet_deserializer.go
pkg/resource/aws/deserializer/vpc_deserializer.go

References
- https://jesseduffield.com/golang-gotcha-of-the-day/#comment-11
- https://github.com/kyoh86/scopelint

Remove reference used in loops

---

pkg/resource/aws/aws_sns_topic_subscription.go

fix policies in topic subscription not beeing tag as jsonstring. So drift will be displayed correctly

fix policies in topic subscription not beeing tag as jsonstring

---

doc/cmd/scan/filter.md

| 🔗 Related issues | [232](https://github.com/cloudskiff/driftctl/issues/232)
I reached out on Discord asking about how to use wildcards in `.driftignore` and was pointed towards trying to use JMES filters first. This PR adds two new examples to `filter.md` which show use of `starts_with` and `ends_with` for filtering resources based on prefixes and suffixes respectively.
Use of the [wildcard operator](https://jmespath.org/specification.html#wildcard-expressions) appears to be limited to iteration over a list as opposed to string matching on a property, so these functions might be the limit. I'd love if someone can …

docs: add more examples to filter.md for prefix/suffix

---

main.go
pkg/cmd/driftctl.go
pkg/cmd/driftctl_test.go
pkg/cmd/errors/errors.go
pkg/cmd/scan.go
pkg/cmd/scan_test.go
pkg/driftctl.go
pkg/iac/supplier/supplier.go
pkg/iac/terraform/state/backend/backend.go
pkg/iac/terraform/state/backend/s3_reader.go
pkg/parallel/parallel_runner.go
pkg/remote/remote.go
pkg/resource/aws/aws_route_ext.go
pkg/scanner.go
pkg/terraform/provider_downloader.go
pkg/terraform/provider_installer.go
sentry/sentry.go
sentry/sentry_test.go

- Remove all `fmt.Errorf` occurences as we do not have stack
- Use `pkg/errors` to allow us to retrieve stack on sentry
- Make `driftctl.Run()` return an error (previously it was hiding us a lot of errors)
- Introduce `UsageError` and makes sentry able to ignore capture of specific error types
- A small rework of usage error output <= that will introduce output BC break
**Before** 
**After**

Better error handling

---

.circleci/config.yml
.github/workflows/homebrew.yml

Change the automation of the homebrew bump formula pipeline from CircleCI to GitHub Actions.

Add homebrew bump formula github action on release event

---

doc/LIMITATIONS.md
pkg/analyser/analyzer.go
pkg/analyser/analyzer_test.go

| 🔗 Related issues | #8
Unmanaged security group rules can be falsely displayed as unmanaged in driftctl scan output. Simply because it's impossible, by only reading the state, to be sure that those rules were created by terraform. Indeed terraform re-writes on apply/refresh the state with all the rules a security group has in AWS if you don't use the egress/ingress in-line blocks. We decided to warn our users if we found rules that were not created with the aws_security_group_rule resource.

Warn on unmanaged security group rules

---

doc/README.md

| 🔗 Related issues | #256 
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context.

Add documentation on log level

---

pkg/alerter/alert.go
pkg/alerter/alerter.go
pkg/alerter/alerter_test.go
pkg/analyser/analysis.go
pkg/analyser/analyzer.go
pkg/analyser/analyzer_test.go
pkg/cmd/scan/output/console.go
pkg/cmd/scan/output/console_test.go
pkg/cmd/scan/output/json_test.go
pkg/cmd/scan/output/output_test.go
pkg/cmd/scan/output/testdata/output_access_denied_alert.json
pkg/cmd/scan/output/testdata/output_access_denied_alert.txt
pkg/middlewares/aws_route_table_expander.go
pkg/middlewares/aws_route_table_expander_test.go
pkg/remote/resource_enumeration_error_handler.go
pkg/remote/resource_enumeration_error_handler_test.go

| 🔗 Related issues | #226 
I modified the composition of the alerts to make it an interface and be able to interact with its type. We can now display the latest up-to-date policy of driftctl if we encounter a denial of access on a resource, specified by its alert.
These changes led me to retouch the tests and add serialisation on the alerts for the JSON marshal part.
I am open to any remark or discussion.

Point to the policy for driftctl when an access denied is encountered

---

pkg/remote/aws/s3_bucket_supplier.go

Fix bucket location returns EU for buckets in eu-west-1

---

.github/workflows/homebrew.yml

Homebrew auto bump formula failed last friday because of the token used. I created a new homebrew github api token on the organization level with our internal account for driftctl and change the yml file to use this secrets.

New Homebrew Secrets

---

pkg/iac/terraform/state/test/cloudfront_distribution/result.golden.json
pkg/iac/terraform/state/test/cloudfront_distribution/terraform.tfstate
pkg/resource/aws/aws_cloudfront_distribution_ext.go

| 🔗 Related issues | #277
It will loop over empty arrays from resources found in the cloud provider to change them into nil to avoid false positives.
For new item, the output will show all the other values that are not `[]` (empty useless array) or `""` (empty string).

Update Cloudfront distribution normalization

---

codecov.yml

Codecov badge should be green as long as we are closed to 70% of coverage.

Change range of coverage colors

---

pkg/middlewares/iam_policy_attachment_sanitizer.go
pkg/middlewares/iam_policy_attachment_sanitizer_test.go
pkg/resource/aws/aws_iam_policy_attachment.go
pkg/resource/aws/deserializer/iam_role_policy_attachment_deserializer.go
pkg/resource/aws/deserializer/iam_user_policy_attachment_deserializer.go

| 🔗 Related issues | #311 
add pointer to user roles and groups
users, roles and groups can be nil but gocty refuse to deserialize in
this case

Fix bug on deserializing aws_iam_policy_attachment

---

pkg/filter/driftignore.go

| 🔗 Related issues | #274 
Just added line index in logger for invalid field in .driftignore, but i don't understand why it print content first and line after, since i set line then content in logrus.Fields{}
Can avoid itoa conversion if index created outer loop scope.

Add line number in log when invalid driftignore line encountered

---

pkg/resource/aws/aws_db_subnet_group.go

| 🔗 Related issues | #327 
the name prefix is a terraform only naming field, we need to ignore it

Fix false positive in aws_db_subnet_group

---

pkg/resource/aws/aws_db_instance.go
pkg/resource/aws/aws_db_instance_ext.go

| 🔗 Related issues | #327 
- `LatestRestorableTime` is a read only attribute, drift does not makes sense
- `SnapshotIdentifier` default value `""` and `nil` should not trigger drift
- `AllowMajorVersionUpgrade` default value `false` and `nil` should not trigger drift
- `ApplyImmediately` default value `false` and `nil` should not trigger drift

Fix false positive drift on aws_db_instance

---

pkg/driftctl.go

It seems that sentry is grouping issues when it shouldn't be

Change error message to avoid unrelated error grouping on sentry

---

.editorconfig
Makefile
goland_watchers.xml
main.go
pkg/cmd/scan.go
pkg/cmd/scan/output/console.go
pkg/cmd/scan/output/console_test.go
pkg/cmd/scan/output/json.go
pkg/cmd/scan/output/json_test.go
pkg/cmd/scan/output/output.go
pkg/cmd/scan/output/output_test.go
pkg/output/printer.go
pkg/remote/aws/provider.go
pkg/remote/terraform/provider.go
pkg/terraform/provider_installer.go

| ⚠ Deprecations?   | yes/no
| 🔗 Related issues | #257 
added printer interface to print info
json output use void printer if the path output is stdout

refacto output print to prevent breaking output isolation

---

pkg/remote/terraform/provider.go

| 🔗 Related issues | #337
When launching a scan, the tool was logging the message "Terraform provider initialized" which means the tool has gained access to the provider's API and is scanning the account, looking for resources in the actual infrastructure. So it can be confusing to the user if you have resources in several regions.

Remove provider initialization message

---

pkg/resource/aws/testdata/acc/aws_dynamodb_table/main.tf

| ❓ Documentation  |no 
remove dynamodb table replica to speed up acc tests

remove dynamodb table replica to speed up acc tests

---

pkg/resource/aws/aws_lambda_function.go

| 🔗 Related issues | #369 
I deleted lastModified field from aws_lambda_function drift report.

Remove LastModified field for aws_lambda_function from drift reports

---

pkg/cmd/driftctl.go

| 🔗 Related issues | #367 
The error reporting flag seems to be confusing.
We need to make it clear that is sends some data to out Sentry server.
So i add an information i found on driftctl-docs error-reporting part to the helper message of the program.

Add details to error reporting flag in help message

---

pkg/analyser/analysis.go
pkg/analyser/testdata/input.json
pkg/analyser/testdata/output.json
pkg/cmd/scan/output/console.go
pkg/cmd/scan/output/testdata/output.json
pkg/cmd/scan/output/testdata/output.txt
pkg/cmd/scan/output/testdata/output_access_denied_alert_aws.json
pkg/cmd/scan/output/testdata/output_access_denied_alert_github.json
pkg/cmd/scan/output/testdata/output_computed_fields.json
pkg/cmd/scan/output/testdata/output_computed_fields.txt
pkg/cmd/scan/output/testdata/output_json_fields.txt
pkg/cmd/scan/output/testdata/output_stringer_resources.txt

| 🔗 Related issues | #372
We should update the wording of the output to be consistent with the summary.
```
Found changed resources:
- 09721498761984 (aws_s3_bucket):
~ Versioning.0.Enabled: false => true
Found 1 resource(s)
- 100% coverage
- 1 covered by IaC
- 0 not covered by IaC
- 0 missing on cloud provider
- 1/1 changed outside of IaC
```

Update output terminology

---

.circleci/config.yml

Following https://github.com/cloudskiff/driftctl/commit/3bf8fe65f99ec8bd764cc31a14fb5474648fcb53, the CI was failing because Go dependencies were missing.

Add missing 'make deps' steps in CI

---

test/acceptance/testing.go

| ❓ Documentation  | none
Allow to set args from check in acceptance test, it will allow to run driftctl multiples times with multiples flags sequentially.

Allow to set args in checks in acceptance test

---

pkg/output/progress.go

| 🔗 Related issues | #371 
Make the number of scanned resources after the spinner during scan reliable and hide progress bar animation when it end.

display last number of resources scanned and hide animation character when progress bar end

---

pkg/analyser/analysis.go
pkg/analyser/analyzer.go
pkg/analyser/analyzer_test.go

| 🔗 Related issues | #374
Differences was expected to be sorted but it turns out the sort was placed at the wrong place in the code, making it completely useless. This PR, which follow the same implementation of #356, intend to fix the issue. We'll surely come across conflicts but they should be easy to resolve.

Make differences output predictable

---

pkg/resource/aws/aws_db_instance.go

| ❌ BC Break       | yes
| 🔗 Related issues | #384
Using the "rds" module, `aws_db_instance` keeps reporting a drifted resource.

Fix false positive report on FinalSnapshotIdentifier field

---

pkg/cmd/scan/output/json.go
pkg/cmd/scan/output/json_test.go
pkg/cmd/scan/output/testdata/output_multiples_times.json

| ❓ Documentation  | none
Add truncate directive to remove file content when writing json output multiples times to the same file

Fix json output

---

Makefile

Prevent `go test` to mess up with go.mod

Prevent go test to update go.mod

---

pkg/iac/terraform/state/terraform_state_reader_test.go
pkg/iac/terraform/state/test/route53_record_null_records/result.golden.json
pkg/iac/terraform/state/test/route53_record_null_records/terraform.tfstate
pkg/middlewares/route53_records_test.go
pkg/resource/aws/aws_route53_record.go
pkg/resource/aws/aws_route53_record_ext.go
pkg/resource/aws/aws_route53_record_test.go
pkg/resource/aws/testdata/acc/aws_route53_record_with_alias/.terraform.lock.hcl
pkg/resource/aws/testdata/acc/aws_route53_record_with_alias/providers.tf
pkg/resource/aws/testdata/acc/aws_route53_record_with_alias/route53.tf

| 🔗 Related issues | #375 
Everything is in the #375 ticket.
We have also fixed new false positive.

Fix aws_route53_record error when deserializing resource (null value is not allowed)

---

pkg/middlewares/aws_route_table_expander.go
pkg/middlewares/aws_route_table_expander_test.go

| 🔗 Related issues | #392
The AWS route table expander middleware was supposed to turn routes embeded in a route table into dedicated resources. But when a route is already a dedicated resource, the scan result shows it as a deleted resource.

Fix false positive on aws_route resources

---

pkg/iac/terraform/state/enumerator/s3.go
pkg/iac/terraform/state/enumerator/s3_test.go

| 🔗 Related issues | #409 
- Ignore directory (size <= 0) when listing bucket object
- Add test for empty directory

Fix #409 do not list directory when using s3 as state backend

---

pkg/iac/terraform/state/backend/http_reader.go
pkg/iac/terraform/state/backend/http_reader_test.go

| 🔗 Related issues | #382
> Using the `--from tfstate+https://` new backend support to access terraform states, if I request the wrong file, I expect to know about it (like "`Sorry, no t3rr4f0rm.tfstate is available at this location`"), more than a json parsing issue (as there's no file to parse obviously) 
This patch returns an explicit error when the HTTP status code is below 200 or above 399.
**Example**
```shell
$  driftctl scan --from tfstate+https://gitlab.com/api/v4/projects/25255199/terraform/state/terraform/versions/1
Scanning resources: ⣻ (0)
error in backend HTTP(s): non-200 OK status code: 401 Unauthorized …
```

Return explicit error on bad http status code

---

pkg/resource/aws/aws_instance.go

| 🔗 Related issues | #403
We figured out that this field is actually not supported by the provider. We decided to simply ignore it for the moment.

Fix false positive on field InstanceInitiatedShutdownBehavior

---

pkg/driftctl_test.go

Testing middlewares that create new resources with a CtyVal attribute.

Start testing middlewares that create resources

---

pkg/cmd/driftctl.go

| 🔗 Related issues | #367 
Fix the #381 PR.

Fix issue 367 error reporting

---

pkg/analyser/analyzer.go

| 🔗 Related issues | #426
Replace a link to limitation documentation by a dedicated deep link.

Use a deep link for known limitations docs

---

pkg/analyser/testdata/input.json

| 🔗 Related issues | https://github.com/cloudskiff/driftctl/pull/429#discussion_r612531346
Fix a typo in JSON testdata. The tests are still passing because that field overridden by the number of element in the differences property.

Rename total_drifted to total_changed in JSON testdata

---

.circleci/config.yml
README.md

| 🔗 Related issues | #405 
Add automatic publish to arch user repository.
Example pipeline can be found there : https://app.circleci.com/pipelines/github/cloudskiff/driftctl/1171/workflows/672dbdd4-d2cb-4ad1-aefe-4af1559288e4/jobs/1845

Publish driftctl to Arch user repository

---

README.md

For prosperity and shoutout to my island, I'd love to see the Reunion Island flag in the readme.

Add Reunion Island flag to readme

---

pkg/driftctl.go

Wrapping error override original error stackstrace and thus makes sentry unable to group issues properly, every issue are grouped in a single event since stack is always the same.
**We should avoid to wrap errors**

Disable useless error wrappings

---

.circleci/config.yml

Due to the recent Codecov breach, we should check the shasum of the bash uploader before using it.

Check codecov shasum before uploading test coverage

---

pkg/iac/terraform/state/terraform_state_reader.go
pkg/iac/terraform/state/terraform_state_reader_test.go
pkg/iac/terraform/state/testdata/v4/invalid_version.tfstate
pkg/iac/terraform/state/testdata/v4/supported_version.tfstate
pkg/iac/terraform/state/testdata/v4/unsupported_version.tfstate
pkg/iac/terraform/state/versions.go
pkg/iac/terraform/state/versions_test.go

| ⚠ Deprecations?   | yes
| 🔗 Related issues | #340
The goal of this patch is to warn the user about the state they provided in case it's from an unsupported version of Terraform.
> It is expected that running driftctl against a terraform state generated by an unsupported version should not be possible and be reported clearly to the user.
>
> In the case of multiple Terraform versions inside a set of tfstates, they should be ignored so at least some execution can happen. This is probably to combine with the future state exclusion feature.
I used [go-version](https://github.com/hashicorp/go-version) by hashicorp to perform the constraint check …

Detect & exclude unsupported Terraform versions 

---

main.go

| 🔗 Related issues | #423
We can't know if something was captured by sentry, so we display a message by default no matter what the user do. This patch remove this message and add a debug log to know when a Sentry report was sent without confusing the user.

Replace Sentry message by debug log

---

.circleci/config.yml

Add the `--ignore-missing` flag to the check of the Codecov's Bash Uploader.

Add ignore-missing flag

---

.circleci/config.yml

Our lambda has now new env var handler outside driftctl scope.
This PR allow us to update only a single env variable in a given lambda function.

Fix version check lambda version bump

---

pkg/cmd/driftctl.go
pkg/cmd/scan.go
pkg/driftctl.go
pkg/telemetry/telemetry.go
pkg/telemetry/telemetry_test.go

| 🔗 Related issues | #441 
Add driftctl telemetry data

Add telemetry

---

pkg/resource/aws/aws_instance_ext.go

| 🔗 Related issues | #419
>  We should display the instance name for aws_ec2_instance and other resource that use tags for a name.

Display ec2 instance name when tag name exist

---

pkg/iac/terraform/state/terraform_state_reader.go
pkg/iac/terraform/state/terraform_state_reader_test.go
pkg/iac/terraform/state/versions.go

| 🔗 Related issues | #340
Tests of the unsupported TF version detection (https://github.com/cloudskiff/driftctl/issues/340#issuecomment-834591744) showed that the message is not formatted properly.
Before : 
After :

Add a missing line break in warning message

---

pkg/cmd/scan.go

| 🔗 Related issues | #476
Previously, the total number of scanned resources was not the same as the one "found". Reason includes resources ignored, filtered, or internally processed. This patch removes the count from the scan progress bar.

Disable count in scan progress bar

---

pkg/iac/terraform/state/test/route/result.golden.json
pkg/resource/aws/aws_route.go

| 🔗 Related issues | #347
2 attributes were missing in the normalization `destination_prefix_list_id` and `instance_owner_id`. Decided to change with the new method `DeleteIfDefault`.

Fix acc tests for aws_route

---

pkg/resource/aws/testdata/acc/aws_db_subnet_group/terraform.tf

Needed 2 subnets in 2 different AZ to make the db_subnet_group work as expected.

Fix terraform file for db_subnet_group

---

pkg/remote/aws/nat_gateway_supplier.go
pkg/remote/aws/nat_gateway_supplier_test.go
pkg/remote/aws/repository/ec2_repository.go
pkg/remote/aws/repository/ec2_repository_test.go
pkg/remote/aws/repository/mock_EC2Repository.go

Add nat_gateway_supplier to ec2_repository to avoid possible hidden dependency.

Add nat_gateways to ec2_repository

---

pkg/remote/aws/route_table_association_supplier.go
pkg/remote/aws/route_table_association_supplier_test.go
pkg/remote/aws/route_table_supplier.go
pkg/remote/aws/route_table_supplier_test.go

Add route_table_supplier/route_table_association_supplier to ec2_repository to avoid possible hidden dependency.

Add route_table and route_table_association to ec2_repository

---

pkg/remote/aws/repository/ec2_repository.go
pkg/remote/aws/repository/ec2_repository_test.go
pkg/remote/aws/repository/mock_EC2Repository.go
pkg/remote/aws/vpc_supplier.go
pkg/remote/aws/vpc_supplier_test.go

Add vpc_supplier to ec2_repository to avoid possible hidden dependency.

Add vpc_supplier to ec2_repository

---

pkg/analyser/analysis.go
pkg/cmd/driftctl.go
pkg/cmd/gen_driftignore.go
pkg/cmd/gen_driftignore_test.go
pkg/cmd/scan.go
pkg/cmd/testdata/input_stdin_empty.json
pkg/cmd/testdata/input_stdin_invalid.json
pkg/cmd/testdata/input_stdin_valid.json
pkg/cmd/testdata/output_stdin_valid.txt
pkg/cmd/testdata/output_stdin_valid_filter.txt
pkg/cmd/testdata/output_stdin_valid_filter2.txt

| 🔗 Related issues | #415
**:warning: NOTICE: this is a backport of #433 into v0.9.0. This feature was removed of v0.8.0 because of UX issues.** The whole feature should be reviewed again. Few improvements has been made in the CLI documentation to help end-user better understand how to use the command.
TL;DR: The purpose of this change is to be able to generate a .driftignore file containing current drifts.
New users can struggle when trying the tool because the output is too large and hard to read. They might want to ignore all the current drifts so they can start introduce the tool in their workflow quickly and fix …

Create driftignore generator command

---

pkg/resource/aws/aws_db_instance_ext.go
pkg/resource/aws/aws_db_instance_test.go
pkg/resource/aws/testdata/acc/aws_db_instance/.terraform.lock.hcl
pkg/resource/aws/testdata/acc/aws_db_instance/db_instance.tf

| 🔗 Related issues | #542 
Fix false positive for aws_db_instance CharacterSetName
Add Acc test.
Maybe it's need to change pkg/iac/terraform/state/test/db_instance/terraform.tfstate and pkg/iac/terraform/state/test/db_instance/result.golden.json, let me know.

Fix aws_db_instance false-positives

---

.circleci/config.yml

Since acceptance tests manage Terraform installation automatically (introduced in  #416), we don't need to install Terraform globally anymore.

Remove terraform installation step in CI

---

pkg/remote/cache/cache.go
pkg/remote/cache/cache_test.go

In some cases, we may want to not use the cache although it's required. It may be for testing purposes or simply because of a technical limitation. We already use a capacity of 0 in supplier unit tests, because we don't need to cache values. For now, a capacity of 0 result in a nil pointer dereference error. This PR fixes the issue simply by ignoring keys when capacity is set to 0.

Fix crash when capacity is set to 0 in cache

---

pkg/iac/terraform/state/backend/http_reader.go
pkg/iac/terraform/state/terraform_state_reader.go

| 🔗 Related issues | #494 
We can't recover summary of errors from the _.HTTPBackend because casting isn't possible with this structure.
So i just add an error check before returning at the end of the method.
Maybe it's need to add some test to keep track of this change, but i'll do it tomorrow after discuss it with the team.

Fix error reporting in http state reader

---

pkg/remote/aws/sns_topic_subscription_supplier.go
pkg/remote/aws/sns_topic_subscription_supplier_test.go

| 🔗 Related issues | #601 
fix #601 by checking arn correctness and sending a different alertt.

fix #601 by checking arn correctness and sending a different alert

---

pkg/remote/aws/init.go
pkg/remote/aws/provider.go
pkg/remote/github/init.go
pkg/remote/github/provider.go
pkg/resource/schemas.go
test/resource/resource.go

| 🔗 Related issues | #446 #457 
Allow to retrieve the provider version and schema version to be used to handle provider issues only for a specific version

Retrieve provider version and schema version

---

pkg/resource/aws/aws_instance.go

| 🔗 Related issues | #446
Previously we disabled diff on this field because of an issue on the provider side. Now this issue has been resolved, we can safely enable the diff back but according to a specific version constraint.

Enable diff on instance_initiated_shutdown_behavior field

---

pkg/iac/terraform/state/enumerator/s3.go

We were using `path.join` to concatenate s3 path but on windows it return a string with backslashes. As it is not really a path we do not have to use `path.join` but `strings.join` with hardcoded `/` character

Fix issue when enumerating s3 states on windows

---

pkg/iac/terraform/state/enumerator/glob.go
pkg/iac/terraform/state/enumerator/s3.go

| 🔗 Related issues | #
Fix usage of wildcards patterns in S3 state enumeration on windows cause by incorrect use of native path separator in a S3 context.

Fix state enumeration on s3 on win when using wildcards

---

pkg/resource/aws/aws_s3_bucket.go

| 🔗 Related issues | #614 
This PR closes #614 by ignoring `bucket_prefix` attribute of `aws_s3_bucket` as it is an internal Terraform property.
The change is trivial and I've tested it in my AWS account, but I can probably add unit tests if needed.

Fix false positive on aws_s3_bucket.bucket_prefix

---

scripts/build.sh

Allows us to cross compile a specific version locally :
```
➜ OS_ARCH=windows/amd64 make build
scripts/build.sh
Bash: 5.1.8(1)-release
+ Building env: dev
ARCH: windows/amd64
+ Removing old binaries ...
+ Building with flags: -X github.com/cloudskiff/driftctl/pkg/version.version=7fe9b13d
Number of parallel builds: 2
-->   windows/amd64: github.com/cloudskiff/driftctl
```

Allow to override OS_ARCH in build script

---

pkg/resource/aws/aws_iam_access_key.go

| 🔗 Related issues | #649 
Fix ses_smtp_password false positive for:
driftctl version: 0.10.0-pre
terraform version: 1.0.0
terraform providers versions: aws@2.70.0
Apparently with the refacto it's not necessary to add a test case ?

Fix ses_smtp_password false positive

---

pkg/cmd/scan.go
pkg/driftctl.go
pkg/iac/terraform/state/terraform_state_reader_test.go
pkg/remote/aws/init.go
pkg/remote/aws/init_test.go
pkg/remote/aws/provider.go
pkg/remote/github/init.go
pkg/remote/github/init_test.go
pkg/remote/github/provider.go
pkg/remote/remote.go
pkg/terraform/provider_config.go
pkg/terraform/provider_installer.go
pkg/terraform/provider_installer_test.go

| 🔗 Related issues | #555 
| ❓ Documentation  | yes - i must add this flag to the documentation
I add a flag 'config-dir' to override the .driftctl default path

Add config-dir flag to change .driftctl location

---

pkg/cmd/scan.go
pkg/resource/schemas.go

| 🔗 Related issues | #646
> As a driftctl user,
> I want to know the version of the provider used by driftctl to scan my account against my tfstate
> So that I can keep my Terraform config in sync with driftctl scan
This PR simply add a log message at the end of scan with the provider's version. Also the default value is now set in the scan command controller, rather than the AWS provider init function.

Display terraform provider version in output

---

pkg/cmd/scan.go
pkg/cmd/scan_test.go
pkg/driftctl.go
pkg/filter/driftignore.go
pkg/filter/driftignore_test.go

| 🔗 Related issues | #618
This PR adds a new driftignore flag to allow user to specify a different filename than .driftignore.

Add driftignore flag to specify a different .driftignore file

---

pkg/driftctl_test.go
pkg/middlewares/aws_role_managed_policy_expander.go

Fix dupplicate resource when expanding managed_policy fields

---

pkg/driftctl.go
pkg/middlewares/tags_all_manager.go
pkg/middlewares/tags_all_manager_test.go

| 🔗 Related issues | #635 and #679
On my first attempt, I tried to create a middleware to just `SafeDelete` each `tags_all` attribute on state and remote resources. But I had huge false positives on `tags` attribute because for remote resources `tags_all` == `tags`.
Thus I created a tags_all manager middleware in which, for the remote resources, I simply `SafeDelete` the `tags_all` attribute and for the state resources, since `tags_all` seems to be
```go
if err := d.Set("tags_all", tags.Map()); err != nil {
return fmt.Errorf("error setting tags_all: %w", err)
}
```
I `SafeSet` `tags_all` to `tags` and delete the former …

Middleware to manage tags_all attribute

---

pkg/cmd/scan.go

| 🔗 Related issues | #550
This PR adds a simple message at the end of the scan to tell the user how much time it took to scan their entire infrastructure.
```shell
Scanned states (1) 
Found 3 resource(s)    
- 100% coverage
Congrats! Your infrastructure is fully in sync.
Done in 8s
Provider version used to scan: 3.19.0. Use --tf-provider-version to use another version.
```

Display elapsed time at end of scan

---

pkg/middlewares/aws_instance_block_device.go
pkg/middlewares/aws_instance_block_device_test.go

| 🔗 Related issues | #562
We should not create a new ebs_volume if the one inlined in `instance.ebs_block_device` was created using `ebs_volume`.

Fix duplicate ebs volume in state

---

pkg/cmd/scan.go

| 🔗 Related issues | https://github.com/cloudskiff/driftctl/issues/550#issuecomment-866643830
According to @sjourdan , this message wasn't clear enough for the user.

Improve scan duration message at end of scan

---

pkg/iac/terraform/state/terraform_state_reader_test.go
pkg/remote/aws/init_test.go
pkg/terraform/provider_installer.go

Since we moved defaults version of provider upper, test fails when updating golden files :

Fix golden files update

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature.md

| 🔗 Related issues | #686
Add need-triage label to new issues so we can easily filter them and process them.

Add need-triage label to new issues

---

pkg/iac/terraform/state/test/lambda_function/result.golden.json
pkg/resource/aws/aws_lambda_function.go

| 🔗 Related issues | #673
We remove `source_code_size` from driftctl as it's a necessary duplicate of `source_code_hash`, and let the user decide to ignore this one or not, using the driftignore.

Ignore source_code_size in aws_lambda_function

---

pkg/envproxy/env_proxy.go
pkg/envproxy/env_proxy_test.go
pkg/iac/terraform/state/backend/s3_reader.go
pkg/iac/terraform/state/backend/s3_reader_test.go
pkg/iac/terraform/state/enumerator/s3.go
pkg/iac/terraform/state/enumerator/s3_test.go

| 🔗 Related issues | #615 
| ❓ Documentation  | yes - https://github.com/cloudskiff/driftctl-docs/pull/83
Creation of a struct to allow override of env var for state enumerator.
I'm not sure with this implementation, feel free to discuss about it.

Add a way to override s3 config/profile with env var

---

pkg/remote/aws/route53_record_enumerator.go
pkg/remote/aws/route53_zone_enumerator.go
pkg/remote/aws/vpc_default_security_group_enumerator.go
pkg/remote/aws/vpc_security_group_enumerator.go

| 🔗 Related issues | #823 
Fix every enumerator to use SupportedType() when needed.

Use SupportedType() in enumerator

---

pkg/iac/terraform/state/testdata/acc/multiple_states/route53/terraform.tf
pkg/iac/terraform/state/testdata/acc/multiple_states/s3/terraform.tf
pkg/iac/terraform/state/testdata/acc/multiple_states_local/route53/terraform.tf
pkg/iac/terraform/state/testdata/acc/multiple_states_local/s3/terraform.tf
pkg/resource/aws/aws_eip_association_test.go
pkg/resource/aws/aws_eip_test.go
pkg/resource/aws/aws_iam_role_test.go
pkg/resource/aws/aws_route_test.go
pkg/resource/aws/testdata/acc/aws_eip/terraform.tf
pkg/resource/aws/testdata/acc/aws_eip_association/mainf.tf
pkg/resource/aws/testdata/acc/aws_iam_access_key/terraform.tf
pkg/resource/aws/testdata/acc/aws_iam_policy_attachment/providers.tf
pkg/resource/aws/testdata/acc/aws_instance/providers.tf
pkg/resource/aws/testdata/acc/aws_route53_record/providers.tf
pkg/resource/aws/testdata/acc/aws_route53_record_with_alias/providers.tf
pkg/resource/aws/testdata/acc/aws_s3_bucket/providers.tf

This PR attempt to fix resource serialization issues in acceptance tests ([example](https://app.circleci.com/pipelines/github/cloudskiff/driftctl/2515/workflows/ff81f09f-c834-4366-bf8c-7618114ebe9e/jobs/4963)). I also pinned provider versions in the `required_providers` directive.
```
DEBU[2902] Reading resources from state backend= path=testdata/acc/aws_route/terraform.tfstate
DEBU[2902] Found module in state module= resourceCount=7
DEBU[2902] Got a cty path error when deserializing state err=unsupported attribute "tags_all" name=vpc type=aws_vpc
DEBU[2902] Successfully converted resource …
```

Use proper provider version in ACC tests

---

test/test_diff.go

Goldenfile update were broken due to new test methods. We try to convert to `cty.Value` complete resource object but it fail with nil value for each field of the schema. We should only serialize resource attributes.

Fix goldenfile update

---

pkg/remote/aws/iam_role_enumerator.go
pkg/remote/iam_scanner_test.go

| 🔗 Related issues | Fix #850 
Path is already contained in AWS listing response 🎉

Add path to `iam_role` in enumerator

---

pkg/remote/aws/ec2_internet_gateway_enumerator.go

Needed to dereference the vpc_id to compare similar strings in `aws_default_internet_gateway` middleware.

Dereference vpc_id

---

pkg/middlewares/aws_default_security_group_rule.go
pkg/middlewares/aws_default_security_group_rule_test.go

Default ingress security group rules should be ignored when deep mode is not enabled.
The problem was that, in non deep mode, rules don't have the `source_security_group` attribute but have the `self` attribute.
Because in the deep mode the `ReadResource` add to the resource both the `source_security_group` attribute and the `self` attribute, let's only rely on the `self` attribute to check default ingress rule.

Fix defaults sgrule middleware to be deep mode compliant

---

pkg/remote/aws/sqs_queue_policy_enumerator.go
pkg/remote/sqs_scanner_test.go

Fix a weakness in sqs queue policy enumerator, sometimes attributes can be `nil`

Fix SQS queue policy crash

---

pkg/resource/aws/aws_instance_test.go

Fix aws_instance acc test by running driftctl in deep mode.

Fix aws_instance acc test

---

pkg/middlewares/aws_route_table_expander.go
pkg/middlewares/aws_route_table_expander_test.go
pkg/remote/aws/ec2_route_enumerator.go
pkg/resource/aws/aws_route.go

Complete the route creation ID function to handle all the cases. Previously it was sending an unexpected alert for theses cases but this is a nonsense.

Handle `destination_prefix_list_id` in `aws_route`

---

pkg/iac/config/config.go
pkg/iac/config/config_test.go
pkg/iac/terraform/state/terraform_state_reader.go
pkg/iac/terraform/state/terraform_state_reader_test.go
pkg/iac/terraform/state/test/source/terraform.tfstate
pkg/resource/resource.go

| 🔗 Related issues | Fix #873 

Add resource source for terraform state

---

pkg/analyser/analyzer_test.go
pkg/analyser/testdata/output.json
pkg/cmd/scan/output/testdata/output.json
pkg/cmd/scan/output/testdata/output_computed_fields.json
pkg/resource/resource.go
test/resource/resource.go

| 🔗 Related issues | #874 
| ❓ Documentation  | https://github.com/cloudskiff/driftctl-docs/pull/90

Add source in JSON output

---

pkg/remote/common/details_fetcher.go
pkg/resource/schemas.go

| ❓ Documentation  | contribution doc
With this new approach we can use remove all boilerplate of custom details fetcher bu setting the resolve func in the schema.
For example for a new resource we'll end with the code below instead of creating a custom detail fetcher:
```go
package gcp
import "github.com/cloudskiff/driftctl/pkg/resource"
const GoogleStorageBucketResourceType = "google_storage_bucket"
func initGoogleStorageBucketMetadata(resourceSchemaRepository resource.SchemaRepositoryInterface) {
resourceSchemaRepository.SetResolveReadAttributesFunc(GoogleStorageBucketResourceType, func(res …
```

Allow to customize read attributes in detail fetcher

---

test/schemas/schemas_test.go
test/schemas/shemas.go
test/terraform/fake_terraform_provider.go

| ❓ Documentation  | contrib doc
This add an helper to generate fake schemas for new provider or new provider version.
It also redirect schemas from fake terraform provider to theses ones. 
It mean that Schema handling is manual and not handled by the `-update` flag in tests.
Ping @moadibfr contribution doc need to be updated according

Add schema creation helper

---

pkg/cmd/scan/output/console.go
pkg/cmd/scan/output/html.go
pkg/cmd/scan/output/html_test.go
pkg/cmd/scan/output/testdata/output.html

| 🔗 Related issues | #921
When we have a diff on a JSON field, the result in the HTML report is ugly. The reason is we use the same formatting function than console output. We should create a custom formatting function.
This PR disables TTY coloring and add missing html tags to the JSON diff.

Fix JSON diff formatting in HTML output

---

pkg/iac/terraform/state/backend/tfcloud_config_reader.go
pkg/iac/terraform/state/backend/tfcloud_config_reader_test.go
pkg/iac/terraform/state/backend/tfcloud_reader.go
pkg/iac/terraform/state/backend/tfcloud_reader_test.go

| 🔗 Related issues | #780 
Whenever possible we should read the terraform configuration file if the user doesn't want to or forget to mention his token with the specific flag `tfc-token`.
Need someone to test on a windows environment.

Should read terraform config file

---

pkg/cmd/scan.go
pkg/cmd/scan/output/config.go
pkg/cmd/scan/output/output.go
pkg/cmd/scan/output/output_test.go
pkg/cmd/scan_test.go

Following a discussion with @eliecharra (https://github.com/cloudskiff/driftctl/pull/865#discussion_r698532633), the options field in the OutputConfig object is not really useful as we only use it for the path and it lacks of type safety. In this PR I removed it in favor of a dedicated `Path` field.

Remove options in output config

---

pkg/cmd/scan/output/console.go
pkg/cmd/scan/output/html_test.go
pkg/cmd/scan/output/output_test.go
pkg/cmd/scan/output/testdata/output.html
pkg/cmd/scan/output/testdata/output.json
pkg/cmd/scan/output/testdata/output.txt
pkg/resource/resource.go

| 🔗 Related issues | #942 
Handle nil source in output to avoid crash.

Fix crash in output when source is nil

---

pkg/cmd/scan.go
pkg/cmd/scan/output/config.go
pkg/cmd/scan/output/output.go
pkg/cmd/scan_test.go
pkg/driftctl.go

| 🔗 Related issues | #831
| ❓ Documentation  | yes https://github.com/cloudskiff/driftctl-docs/pull/86 
```bash
$ driftctl scan -o console://stdout -o html://reports/001/result.html -o json://reports/001/result.json
```

Allow multiple output flags for a single scan

---

pkg/remote/azurerm/common/config.go
pkg/remote/azurerm/provider.go

| ❌ BC Break       | yes
| ❓ Documentation  | https://github.com/cloudskiff/driftctl-docs/pull/111
It was a mistake to reuse terraform env vars, the azure SDK uses another env var naming which can cause issues.

Fix azure authentication

---

pkg/resource/github/testdata/acc/github_branch_protection/terraform.tf

Reference : https://github.com/integrations/terraform-provider-github/issues/908

Fix github acceptance test

---

go.mod
go.sum
pkg/cmd/driftctl.go
pkg/cmd/scan.go
pkg/cmd/scan_test.go
pkg/cmd/testdata/terraform_invalid.lock.hcl
pkg/cmd/testdata/terraform_valid.lock.hcl
pkg/remote/aws/init.go
pkg/remote/aws/provider.go
pkg/remote/azurerm/init.go
pkg/remote/azurerm/provider.go
pkg/remote/common/providers.go
pkg/remote/github/init.go
pkg/remote/github/provider.go
pkg/remote/google/init.go
pkg/remote/google/provider.go
pkg/remote/terraform/provider.go
pkg/terraform/lock/lockfile.go
pkg/terraform/lock/lockfile_test.go
pkg/terraform/lock/testdata/lockfile_empty.hcl
pkg/terraform/lock/testdata/lockfile_invalid.hcl
pkg/terraform/lock/testdata/lockfile_invalid_type-1.hcl
pkg/terraform/lock/testdata/lockfile_invalid_type-3.hcl
pkg/terraform/lock/testdata/lockfile_valid.hcl

| 🔗 Related issues | #929
| ❓ Documentation  | https://github.com/cloudskiff/driftctl-docs/pull/130 
This PR implement a lock package that parses the content of a Terraform lock file. This logic is used in the Terraform supplier in order to install a specific version when we found a Terraform lock file in at the given path.

Read provider version from .terraform.lock.hcl lock file when possible

---

pkg/iac/terraform/state/terraform_state_reader_test.go
pkg/iac/terraform/state/test/api_gateway_api_key/results.golden.json
pkg/iac/terraform/state/test/api_gateway_api_key/terraform.tfstate
pkg/remote/api_gateway_scanner_test.go
pkg/remote/aws/api_gateway_api_key_enumerator.go
pkg/remote/aws/init.go
pkg/remote/aws/repository/api_gateway_repository.go
pkg/remote/aws/repository/api_gateway_repository_test.go
pkg/remote/aws/repository/mock_ApiGatewayRepository.go
pkg/resource/aws/aws_api_gateway_api_key.go
pkg/resource/aws/aws_api_gateway_api_key_test.go
pkg/resource/aws/testdata/acc/aws_api_gateway_api_key/.terraform.lock.hcl
pkg/resource/aws/testdata/acc/aws_api_gateway_api_key/terraform.tf
pkg/resource/resource_types.go

| 🔗 Related issues | #960
| ❓ Documentation  | https://github.com/cloudskiff/driftctl-docs/pull/123
Add `aws_api_gateway_api_key` resource

Add api_gateway_api_key

---

pkg/resource/deserializer.go

| 🔗 Related issues | https://github.com/cloudskiff/driftctl/issues/947#issuecomment-932175905
This PR fixes an issue discovered by @sjourdan caused by sensitives values in Terraform that prevents the resource to be deserialized. Marked values cannot be deserialized, which requires us to unmark the cty value.

Remove marks from values in the deserializer

---

pkg/driftctl.go
pkg/iac/terraform/state/terraform_state_reader_test.go
pkg/iac/terraform/state/test/api_gateway_stage/results.golden.json
pkg/iac/terraform/state/test/api_gateway_stage/terraform.tfstate
pkg/middlewares/aws_api_gateway_deployment_expander.go
pkg/middlewares/aws_api_gateway_deployment_expander_test.go
pkg/remote/api_gateway_scanner_test.go
pkg/remote/aws/api_gateway_stage_enumerator.go
pkg/remote/aws/init.go
pkg/remote/aws/repository/api_gateway_repository.go
pkg/remote/aws/repository/api_gateway_repository_test.go
pkg/remote/aws/repository/mock_ApiGatewayRepository.go
pkg/resource/aws/aws_api_gateway_deployment.go
pkg/resource/aws/aws_api_gateway_stage.go
pkg/resource/aws/aws_api_gateway_stage_test.go
pkg/resource/aws/testdata/acc/aws_api_gateway_stage/.terraform.lock.hcl
pkg/resource/aws/testdata/acc/aws_api_gateway_stage/terraform.tf
pkg/resource/resource_types.go

| 🔗 Related issues | #960
| ❓ Documentation  | https://github.com/cloudskiff/driftctl-docs/pull/134
Add `aws_api_gateway_stage` resource.
The middleware is needed to avoid missing stages created inline by `aws_api_gateway_deployment`, a resource dropped from our last voice call last week with @eliecharra and @sjourdan

Add api_gateway_stage resource

---

go.mod
pkg/middlewares/aws_api_gateway_rest_api_expander.go
pkg/middlewares/aws_api_gateway_rest_api_expander_test.go

| 🔗 Related issues | #1203
Add the same yaml package as the one used in the kin-openapi package to parse OpenAPI document.
After we try to unmarshall json document, if it fails due to syntax error, let's try to unmarshall with the yaml format.

Middleware should handle YAML body document now

---

go.mod

Following #1204, that yaml dependency was mistakenly added as a indirect dependency, but `go mod tidy` disagrees.

Put github.com/ghodss/yaml as direct dependency

---

pkg/cmd/scan.go
pkg/cmd/scan/output/output.go
pkg/cmd/scan/output/output_test.go

| 🔗 Related issues | #1211
As reported by @moadibfr, the progress bar and other global output usage were hidden because as we implemented multiple output (#865), the global output was always assigned to the `voidPrinter` which prints nothing. This PR fixes that by setting the global output **before** the scan.

Display progress bar in stdout

---

pkg/cmd/scan.go
pkg/iac/terraform/state/backend/backend.go
pkg/iac/terraform/state/backend/tfcloud_config_reader.go
pkg/iac/terraform/state/backend/tfcloud_config_reader_test.go
pkg/iac/terraform/state/backend/tfcloud_reader.go
pkg/iac/terraform/state/backend/tfcloud_reader_test.go

| ❓ Documentation  | https://github.com/cloudskiff/driftctl-docs/pull/181
Documentation claims that Terraform Enterprise is supported, but there was no option to pass in the Terraform Enterprise URL.  This adds an option to pass in the Terraform Enterprise URL, --tfc-api "https://tfe.domain.net/api/v2", with the default for existing behavior.

Support passing in the Terraform API URL to support Terraform Enterprise installations.

---

pkg/remote/azurerm/provider.go

Azure provider registration allow terraform provider to automatically
register azure resource providers.
In our context we are running read only so we do not want to try to
enable them during the scan.
Without this, a driftctl scan will try to register resource providers
since it is done in the gRPC configure call.

Force azure provider registration to false.

---

pkg/remote/azurerm/azurerm_private_dns_cname_record_enumerator.go
pkg/remote/azurerm/azurerm_privatedns_a_record_enumerator.go
pkg/remote/azurerm/azurerm_privatedns_aaaa_record_enumerator.go
pkg/remote/azurerm/azurerm_privatedns_mx_record_enumerator.go
pkg/remote/azurerm/azurerm_privatedns_ptr_record_enumerator.go
pkg/remote/azurerm/azurerm_privatedns_srv_record_enumerator.go

| ❌ BC Break       | o
| 🔗 Related issues | #1063 
Running a non-deep mode scan on those resources produces a panic since some attributes return a pointer instead of a value. This behavior is not covered by unit tests since we only test those resources against deep mode.
```
panic: interface conversion: interface {} is *string, not string
goroutine 1 [running]:
github.com/cloudskiff/driftctl/pkg/resource.(*Attributes).GetString(...)
/home/<redacted>/cloudskiff/driftctl/pkg/resource/resource.go:168
[...]
```

Fix private DNS resources attributes

---

test/acceptance/testing_test.go

The test for the retry logic was failing unexpectedly in random branches because the configured timeout (1ms) is too short so the timeout sometimes exceed before the test function is executed ([example](https://app.circleci.com/pipelines/github/cloudskiff/driftctl/3784/workflows/b5d7a14a-785a-4b77-8de0-c401691fd05e/jobs/7695)). I've set the timeout to 100ms so it doesn't bother us again.

Fix inconsistent test for RetryFor

---

pkg/cmd/driftctl_test.go
pkg/cmd/version_test.go

In some particular context (when packaging driftctl in release mode, check [nixpkg](https://github.com/NixOS/nixpkgs/commit/ded247ada384ceacc5d0d186cffa7c1cc927d268#diff-f6248b889160cf7652be9255c593b1ded04177a6d33449c69b8f4e4abf28ce57R45-R47)) theses test are failing since the version `dev-dev`is hardcoded.
This PR make sure that they will match the current version regardless of any ldflags.

Make version check test more dynamic

---

build/build.go
main.go
pkg/cmd/driftctl.go
pkg/cmd/driftctl_test.go
pkg/cmd/scan.go
pkg/telemetry/telemetry.go
pkg/telemetry/telemetry_test.go
test/build.go
test/mocks/MockBuild.go

This PR is adding a more convenient way to disable any third-party network calls.
You can now build an telemetry-free version of driftctl easily with 
```shell
$ go build -ldflags="-X 'github.com/cloudskiff/driftctl/build.enableThirdPartyNetworkCalls=false'" 
```
- https://github.com/NixOS/nixpkgs/commit/ded247ada384ceacc5d0d186cffa7c1cc927d268#diff-f6248b889160cf7652be9255c593b1ded04177a6d33449c69b8f4e4abf28ce57R31-R38

Add a global switch to disable third party

---

test/acceptance/testing.go

In acceptance testing environment, usage report has been disabled, this means --disable-telemetry and --no-version-check flags are not supported. This PR removes it to prevent having this error : `unknown flag: --disable-telemetry`

Fix acceptance cli arguments

---

scripts/changelog.sh

This bash script uses the GH CLI to generate a changelog from the previous tag to a base branch. It must be ran **before** creating the new release's tag.

Create changelog generator script

---

.circleci/config.yml

Enable snyk code scanning for commits approved by maintainers.
This is a workaround that will provide maintainers with visibility into potential vulnerabilities.

chore: enable oss & code scans for maintainers

---

.snyk

MPL-2.0 license is used by hashicorp libraries. We are acknowledging the use of it by including the information in each release. This PR adds snyk ignore to silence the warnings.

chore: ignore mpl-2 license warnings

---

pkg/resource/aws/aws_lambda_event_source_mapping_test.go

For QA purposes, if event source mappings are yet to be deleted but not found in the console you can still use CLI commands. This PR adds those commands in the test file.

chore: add commands to list and delete event source mappings

---

.goreleaser.yml

Let's disable this since it break release builds because of an issue with azure sdk (again and always ...)
```
one or more libraries have an incompatible/unknown license: map["unknown":["github.com/Azure/azure-sdk-for-go/sdk/internal/log" "github.com/Azure/azure-sdk-for-go/sdk/internal/diag" "github.com/Azure/azure-sdk-for-go/sdk/internal/errorinfo" "github.com/Azure/azure-sdk-for-go/sdk/internal/uuid"]]
```
This reverts commit caabac2bee7e5c1e6cd1b93086aed611634090b9.

Revert "chore: add licensing acknowledgments"

---

.circleci/config.yml

This context contain the GITHUB_TOKEN env var needed to publish a new release. We previously used this context but for some reason we dropped it when moving from cloudskiff to snyk.

Add missing circleci context

---

pkg/remote/google/google_compute_network_enumerator.go
pkg/resource/google/google_compute_network.go

A recent acceptance test run catched this bug where attributes from the `google_compute_network` enumerator doesn't match the Terraform schema of the resource.
See https://app.circleci.com/pipelines/github/snyk/driftctl/3961/workflows/b530585a-c6d4-4cf2-8f22-159fbf672d84/jobs/8157

Fix google_compute_network read attributes

---

.circleci/config.yml

This PR goal is to speed-up test check in PRs
- Use larger circleci executors
- Update circleci/go orb: allow us to reuse go binary cache
- Add go mod caching
**Before**
**After**

User large circleci executors

---

pkg/remote/google/google_compute_subnetwork_enumerator.go
pkg/resource/google/google_compute_subnetwork.go

Just like #1290, https://github.com/snyk/driftctl/pull/1197
A recent acceptance test run catched this bug where attributes from the google_compute_subnetwork enumerator doesn't match the Terraform schema of the resource.
See https://app.circleci.com/pipelines/github/snyk/driftctl/3979/workflows/91c85c7e-7362-4497-b41f-98ac8397c194/jobs/8231

 Fix google_compute_subnetwork attributes

---

pkg/iac/terraform/state/backend/gs_reader.go
pkg/iac/terraform/state/backend/gs_reader_test.go
pkg/iac/terraform/state/backend/testdata/gcp_application_default_credentials.json

Following https://github.com/snyk/driftctl/pull/1282#issuecomment-995863330, we shouldn't perform any IO/network operations in a constructor. This PR improves testing of the GCS backend: we never use the non-mocked storage client in tests to avoid IO/network operations. In a real world execution, the storage client is created in the `Read` method.

Improve testing for the GCS backend

---

.circleci/config.yml

Reduce the time of test.
We want to keep the machine executor for acc tests since they are more heavy.
**Before**
**After**

Use docker executor for tests

---

.gitignore
scripts/build.sh
scripts/changelog.sh

As we now want to release early and often, this PR updates the goreleaser config in order to write the release changelog automatically. I also edited the actual changelog generator script, code was slightly simplified and it doesn't add empty changelog sections anymore. CHANGELOG.md was added to the gitignore file so the git state doesn't get dirty when releasing (goreleaser doesn't like that).
Output example: 
**Before**:
```shell
$ GITHUB_TOKEN=<redacted> ./scripts/changelog.sh
Generating changelog for commits from origin/HEAD to v0.18.1...
- Fix google_compute_subnetwork attributes (#1293) …
```

Add custom changelog to goreleaser command

---

.circleci/config.yml

This PR installs the github-cli in CI pipelines and edit the changelog script to authenticate using the GITHUB_TOKEN env variable.
- https://circleci.com/developer/orbs/orb/circleci/github-cli
- https://cli.github.com/manual/

Configure github-cli in circleci

---

scripts/build.sh

The last release failed to use the proper release notes. The generated changelog will now be showed in the logs. Also bump goreleaser version to v1.1.0.
In the meantime, I've opened https://github.com/goreleaser/goreleaser/issues/2778 to ensure it's not a bug from goreleaser.

Update goreleaser config & version

---

scripts/changelog.sh

Since the tag is already created when releasing, we need to compare commits based on the second most recent tag, not the default branch. For now we just get an empty changelog so goreleaser fallback to its default changelog generator.

Use second most recent tag in changelog script

---

pkg/resource/google/google_bigquery_table_test.go

This test failed in our nightly run but used to succeed in previous runs. I cannot reproduce locally so I suggest this is just about the resource not being visible in the API immediately, this is the case for 7 other GCP resources.

Fix acceptance test for google_bigquery_table

---

pkg/middlewares/google_iam_binding_tranformer_test.go
pkg/middlewares/google_iam_binding_transformer.go

| 🔗 Related issues | #1311 
Fix a weakness in the GCP IAM binding transformer

Fix crash in GCP iam binding middleware

---

scripts/changelog.sh

This PR improve the changelog generator script so it better handle patch releases. We were previously using tags created from the default branch (main) to analyze commit history but it doesn't work for patch releases since they're created from another branch. Those changes ensure we compare the right tags to generate the changelog.

Handle patch releases in changelog script

---

pkg/resource/aws/testdata/acc/aws_api_gateway_stage/terraform.tf

We [recently experienced this error](https://app.circleci.com/pipelines/github/snyk/driftctl/4069/workflows/ce8eabc7-3fc6-45fb-94f5-ac4d223b688a/jobs/8568) in nightly tests : 
```
=== RUN   TestAcc_Aws_ApiGatewayStage
[...]
Error: Error creating API Gateway Deployment: ConflictException: Another Deployment is in progress for rest api with id ljzdvh62d7 . Please try again later.
```
This PR attempt to fix acceptance test for resource `aws_api_gateway_stage`. I removed one of the deployment so it doesn't conflict with the other one.

Fix acceptance test for aws_api_gateway_stage

---

pkg/driftctl.go
pkg/middlewares/aws_api_gateway_api_expander.go
pkg/middlewares/aws_api_gateway_api_expander_test.go

This middleware is no more only about rest API (v1) and should take into account v2 as well. I also add `(apigatewayv2)` at the end of v2 tests of this middleware to avoid confusion.

chore: change namings in the apigtw api middleware

---

pkg/driftctl.go
pkg/iac/terraform/state/terraform_state_reader_test.go
pkg/iac/terraform/state/test/aws_apigatewayv2_domain_name/results.golden.json
pkg/iac/terraform/state/test/aws_apigatewayv2_domain_name/terraform.tfstate
pkg/middlewares/aws_api_gateway_domain_names_reconciler.go
pkg/middlewares/aws_api_gateway_domain_names_reconciler_test.go
pkg/remote/aws/apigatewayv2_domain_name_enumerator.go
pkg/remote/aws/init.go
pkg/remote/aws_apigatewayv2_scanner_test.go
pkg/resource/aws/aws_apigatewayv2_domain_name.go
pkg/resource/aws/aws_apigatewayv2_domain_name_test.go
pkg/resource/aws/metadata_test.go
pkg/resource/aws/testdata/acc/aws_apigateway_v1v2_domain_names/.driftignore
pkg/resource/aws/testdata/acc/aws_apigateway_v1v2_domain_names/.terraform.lock.hcl
pkg/resource/aws/testdata/acc/aws_apigateway_v1v2_domain_names/terraform.tf
pkg/resource/aws/testdata/acc/aws_apigatewayv2_domain_name/.driftignore
pkg/resource/aws/testdata/acc/aws_apigatewayv2_domain_name/.terraform.lock.hcl
pkg/resource/aws/testdata/acc/aws_apigatewayv2_domain_name/terraform.tf
pkg/resource/resource_types.go

| 🔗 Related issues | #1257 
| ❓ Documentation  | https://github.com/snyk/driftctl-docs/pull/211
Needed to add a new middleware to handle the reconciliation between `aws_api_gateway_domain_name` (v1) and `aws_apigatewayv2_domain_name` (v2) resources.
The all explanation can be easily sum up by a small example:
```hcl
resource "aws_api_gateway_domain_name" "foo" {
domain_name              = "foo.example.com"
regional_certificate_arn = aws_acm_certificate.foo.arn
endpoint_configuration {
types = ["REGIONAL"]
}
}
resource "aws_apigatewayv2_domain_name" "bar" {
domain_name = "bar.example.com"
domain_name_configuration {
certificate_arn = …
```

Add aws_apigatewayv2_domain_name resource

---

pkg/resource/aws/testdata/acc/aws_apigatewayv2_vpc_link/terraform.tf

Sometimes we got this error in our acc test:
```
Error: error creating API Gateway v2 VPC Link: BadRequestException: Subnet 'subnet-0fc248a9afd376dba' is in Availability Zone 'use1-az3' where service is not available
with aws_apigatewayv2_vpc_link.foo,
on terraform.tf line 24, in resource "aws_apigatewayv2_vpc_link" "foo":
24: resource "aws_apigatewayv2_vpc_link" "foo" {
: exit status 1
```
This PR will fix this issue by assigning a specific availability zone each time we create subnets.

fix: assign a specific az while creating subnets

---

pkg/resource/google/google_bigquery_dataset_test.go
pkg/resource/google/google_bigquery_table_test.go
pkg/resource/google/google_bigtable_instance_test.go
pkg/resource/google/google_bigtable_table_test.go
pkg/resource/google/google_cloudfunctions_function_test.go
pkg/resource/google/google_sql_database_instance_test.go
pkg/resource/google/google_storage_bucket_test.go

As per a discussion with @craigfurman on [CFG-1305](https://snyksec.atlassian.net/browse/CFG-1305), we agreed that retrying the scan in a tight loop was not ideal and we should use some linear or exponential sleep-backoff instead. The common problem that seem to affect all GCP acc tests is that the asset API sometimes return cached result, making new resource appear as missing ([example](https://app.circleci.com/pipelines/github/snyk/driftctl/4118/workflows/5ab1d12f-eb0b-40c2-bdf1-cad9a47dd1b6/jobs/8763)). The [GCP docs](https://cloud.google.com/asset-inventory/docs/faq#result-stale) says : 
> Data freshness in the Cloud Asset API is on a best-effort basis. While almost all asset updates will be available to clients in minutes, in rare cases it's possible the result of the Cloud Asset API …

Add sleep-backoff to GCP ACC tests [CFG-1305]

---

pkg/driftctl.go
pkg/middlewares/aws_default_api_gateway_account.go
pkg/middlewares/aws_default_api_gateway_account_test.go

| 🔗 Related issues | #1217
> We all have an aws_api_gateway_account resource inside each region of AWS that will by default output as unmanaged. We should ignore this one unless you manage it by Terraform.
This PR adds a simple middleware to ignore remote `aws_api_gateway_account` resources when it's not managed by Terraform.
**Notes to reviewers**:
- I didn't find a way to differentiate default and managed resources, so beware of the impact of this change
- This middleware will not run in strict mode

Ignore default aws_api_gateway_account resources

---

pkg/resource/aws/metadata_test.go

I added a missing test for the `TestAWS_Metadata_Flags`  and regroup all api gateway v2 resources inside this same file

chore: added a missing test and ordered resources

---

.circleci/config.yml

This PR fixes a bad string concatenation in the curl command we use to trigger a workflow run in the docs repository. Currently, the header doesn't use the `GITHUB_TOKEN` variable well, resulting in [a "bad credentials" response](https://app.circleci.com/pipelines/github/snyk/driftctl/4150/workflows/6deb3dbd-e68c-4302-af31-872b3e014700/jobs/8888).

Fix string concatenation in curl command

---

main.go
pkg/cmd/scan/output/console.go
pkg/cmd/scan/output/testdata/output.txt
pkg/cmd/scan/output/testdata/output_computed_fields.txt
pkg/cmd/scan/output/testdata/output_empty_attributes.txt
pkg/cmd/scan/output/testdata/output_json_fields.txt
pkg/cmd/scan/output/testdata/output_stringer_resources.txt
pkg/cmd/scan/output/testdata/output_without_deep.txt

| 🔗 Related issues | None
A quick 💅 
- removing redundant space before exclamation mark in output
- capitalizing `Terraform` in output for consistency and correctness, currently we have once no-capitalized and twice capitalized.

Capitalize terraform in output

---

pkg/resource/google/google_compute_global_address_test.go

After observing failure in [a recent nightly test](https://app.circleci.com/pipelines/github/snyk/driftctl/4167/workflows/0b6e137c-e0c5-482b-a614-11a7bdf8dd40/jobs/8962), this PR adds a retry policy to a GCP acceptance test.

Add retry policy to google_compute_global_address acc test

---

pkg/resource/google/google_bigquery_table_test.go
pkg/resource/google/google_compute_global_address_test.go
test/acceptance/testing.go

Those particular tests seems to have more regression than others. This PR increases the retry duration from 10 to 15 minutes so it will retry one more time after sleeping for 8 min.
```
Retry count 	0  1  2  3   4 
Sleep 	 	0  2  4  6   8
Retry duration	0  2  6  12  20  # Stopping here since 20>15
```
Also added a field `retry_duration` to debug logs so we can figure out the elapsed time for this test to pass/fail in the future.
- https://app.circleci.com/pipelines/github/snyk/driftctl/4187/workflows/0e27db19-91a1-4355-b081-a130a3e6d741/jobs/9040
- https://app.circleci.com/pipelines/github/snyk/driftctl/4182/workflows/716a9d08-c662-47c9-b9f1-d52d756290de/jobs/9020
- https://app.circleci.com/pipelines/github/snyk/driftctl/4167/workflows/0b6e137c-e0c5-482b-a614-11a7bdf8dd40/jobs/8962

Update retry policy for GCP acc tests

---

pkg/resource/google/google_bigquery_dataset_test.go
pkg/resource/google/google_bigquery_table_test.go
pkg/resource/google/google_bigtable_instance_test.go
pkg/resource/google/google_bigtable_table_test.go
pkg/resource/google/google_cloudfunctions_function_test.go
pkg/resource/google/google_compute_global_address_test.go
pkg/resource/google/google_compute_instance_test.go
pkg/resource/google/google_compute_network_test.go
pkg/resource/google/google_sql_database_instance_test.go
pkg/resource/google/google_storage_bucket_test.go
test/acceptance/testing.go

This PR adds a retry policy for some GCP tests that failed recently without retrying. It also creates a new common `LinearBackoff` function so we don't duplicate the retry policy for each test.
Tests where I added the retry policy : 
- `TestAcc_Google_ComputeInstance`
- `TestAcc_Google_ComputeNetwork`
**References**
- https://app.circleci.com/pipelines/github/snyk/driftctl/4195/workflows/5e665d3d-db9e-485b-bc29-1b106fd9846a/jobs/9071

Add retry policy for remaining GCP acc tests

---

.circleci/config.yml
scripts/issue-tagging.sh

As discussed in [CFG-1344](https://snyksec.atlassian.net/browse/CFG-1344) : 
> We want to have a mechanism to flag issues (by adding a comment, a label, milestone, whatever) to the version there were released. 
This PR creates a `issue-tagging` script that automatically flag fixed issues with a milestone when we release a new version of driftctl. For example, let's say we release v1.0.2 that fixes issue #A and #B, running this script will create a milestone `v1.0.2` (if it doesn't exist already) and add it to issue #A and #B. It will also add a comment to notify the OP that a new version is available.
I've searched for existing bots or software that would do what we want but found nothing that really fits with our needs. If you think this script is too much to deal with, let me know.
- …

Add issue-tagging script

---

main.go
pkg/cmd/scan/exit_codes.go
pkg/remote/terraform/provider.go

| 🔗 Related issues | https://github.com/snyk/driftctl/issues/1350
`driftctl scan` exits with zero only when there is no detected drift.
Prior to this commit, it exited with 1 when there was a non-panic error,
and also when there was detected drift. This makes error handling in
scripts more awkward than it needs to be.
This commit changes the exit code to 2 whenever there are errors during
a scan, whether that error is from a panic or not, leaving 1 as the exit
code used solely for when drift is detected.
Related: https://github.com/snyk/driftctl/issues/1350
---
I grepped the codebase for `os.Exit`, I think I …

Disambiguate between drift and error exit codes

---

pkg/resource/resource.go

| 🔗 Related issues | #1325
added `human_readable_attributes` field to json output e.q.
```json
{
"id": "sgrule-1180062852",
"type": "aws_security_group_rule",
"human_readable_attributes": {
"Destination": "0.0.0.0/0",
"Ports": "All",
"Protocol": "All",
"SecurityGroup": "sg-08e4f811ab524c960",
"Type": "egress"
}
}
```
```json
{
"id": "nacl-4081969105",
"type": "aws_network_acl_rule",
"human_readable_attributes": {
"CIDR": "0.0.0.0/0",
"Egress": "true",
"Network": "acl-4f2eda2b",
"Protocol": "All",
"Rule number": "100"
}
}
```

adding `humanReadableAttributes` to JSON output

---

pkg/cmd/scan/output/output.go
pkg/cmd/scan/output/output_test.go

| 🔗 Related issues | #1358
We should not print anything but the scan output when we send output to stdout.

Use voidprinter when sending HTML output to stdout

---

pkg/analyser/analysis.go
pkg/analyser/analyzer.go
pkg/analyser/analyzer_test.go
pkg/cmd/scan.go
pkg/cmd/scan/output/console.go
pkg/cmd/scan/output/console_test.go
pkg/cmd/scan/output/output_test.go
pkg/cmd/scan/output/testdata/output_with_only_managed.txt
pkg/cmd/scan/output/testdata/output_with_only_unmanaged.txt
pkg/cmd/scan_test.go
pkg/driftctl.go
pkg/remote/scanner.go

| ❓ Documentation  | https://github.com/snyk/driftctl-docs/pull/223
This PR adds 2 new flags that will output a different summary at the end of the scan. 
The `--only-managed` flag should sum up what's under control only in your states:
```
Found missing resources:
- vol-xxxx (aws_ebs_volume)
From tfstate://terraform.tfstate
- i-xxxxx (aws_instance.bar)
Found changed resources:
From tfstate://terraform.tfstate
- i-xxxxxx (aws_instance.foo):
~ instance_type: "t2.nano" => "t2.micro" (computed)
Found 4 resource(s)
- 50% coverage
- 2 resource(s) managed by Terraform
- 1/2 resource(s) out of sync with Terraform state
- 2 …
```

New --only-managed / --only-unmanaged flags

---

scripts/changelog.sh

This PR slightly improve the changelog generator script.
Since #1361, we don't check if categorised changes are empty, so it makes the changelog look like this : 
```md
- New --only-managed / --only-unmanaged flags (#1359) @wbeuil 
- Fix issue tagging script (#1362) @sundowndev 
- chore: fix failed ACC tests (#1363) @eliecharra 
```
But we want to filter out empty categories instead : 
```md
- New --only-managed / --only-unmanaged flags (#1359) @wbeuil
- Fix issue tagging script (#1362) @sundowndev
- chore: fix failed ACC tests (#1363) @eliecharra
```
I also renamed "Uncategorised" to "Other contributions", which I think is more explicit.

Check for empty categories in changelog script

---

pkg/analyser/analysis.go
pkg/analyser/analyzer_test.go
pkg/analyser/testdata/input.json
pkg/analyser/testdata/output.json
pkg/cmd/scan/output/output_test.go
pkg/cmd/scan/output/testdata/output.json
pkg/cmd/scan/output/testdata/output_access_denied_alert_aws.json
pkg/cmd/scan/output/testdata/output_access_denied_alert_github.json
pkg/cmd/scan/output/testdata/output_computed_fields.json
pkg/cmd/scan/output/testdata/output_multiples_times.json
pkg/driftctl.go
pkg/driftctl_test.go

| 🔗 Related issues | #1370
| ❓ Documentation  | https://github.com/snyk/driftctl-docs/pull/224 
>  We should have the total number of sources scanned during the scan in the summary and output it our JSON format.
This PR adds a new JSON field to the scan output.

Add total_iac_source_count json field

---

main.go
pkg/cmd/scan/output/output.go
pkg/cmd/scan/output/output_test.go
pkg/output/printer.go

- Add `IS_SNYK` parameter to know whether we are used in snyk CLI
- Enable colorization when piped in snyk CLI
- Log diagnostic output to stderr (allow to get the progressbar when piped with snyk)

Improve snyk piping

---

pkg/remote/aws/apigatewayv2_mapping_enumerator.go
pkg/remote/aws_apigatewayv2_scanner_test.go
pkg/resource/aws/aws_apigatewayv2_mapping.go

User on Discord recently reported a crash happening while scanning cloud resources. [Stack trace in crash report](https://sentry.io/organizations/snyk/issues/3079840329/?project=5568568&query=is%3Aunresolved) showed that it's the `apigatewayv2_mapping` enumerator using `nil` as values for `stage` and `api_id`.
```
*errors.fundamental: A runner routine paniced: runtime error: invalid memory address or nil pointer dereference
File "/root/project/pkg/parallel/parallel_runner.go", line 94, in (*ParallelRunner).Run.func1.1
File "/root/project/pkg/remote/aws/apigatewayv2_mapping_enumerator.go", line …
```

Fix panic in apigatewayv2_api_mapping enumerator

---

pkg/resource/aws/testdata/acc/aws_rds_cluster_instance/terraform.tf

Acceptance tests were failing the past 2-3 days because of a wrong configuration of instance class for rds.
`db.r4.large` instance class can't be associated with Postgre 13 versions as per this screenshot

fix: change instance class for the rds cluster

---

pkg/remote/aws_route53_scanner_test.go

This PR bring a light change to the AWS scanner tests. The name parsing for route53 records were not really relevant since it didn't test the new behavior.

test: route53 name parsing

---

.goreleaser.yml

> It would be good to serve DriftCtl binary from [static.snyk.io](http://static.snyk.io/) and have the Snyk CLI download it from there.
This PR adds a config option to upload release artifacts to the `snyk-assets` S3 bucket.

[CFG-1601] Add blobs config to goreleaser file

---

scripts/issue-tagging.sh

**chore: remove duplicates in array**
Added a line to remove duplicates entries in the ISSUES variable. This can happen when we compare two branches where merge commits were cherry-picked (e.g. patch releases).
**chore: fix issue parsing in issue tagging script**
Following https://github.com/snyk/driftctl/pull/1444, this PR fixes the regex that parses the issue identifier in pull requests.
Example:
```bash
$ gh pr view 1443 --json body | grep -oE '(Related issues \| )(.*)?[0-9]+(.*|\r|\n)?(\|)' | sed 's/[^[:digit:]]//g' | sed -z 's/\n//g'
$ gh pr view 1379 --json body | grep -oE '(Related issues \| )(.*)?[0-9]+(.*|\r|\n)?(\|)' | sed 's/[^[:digit:]]//g' | sed -z 's/\n//g'
998%
$ gh pr view 1444 --json body | grep -oE '(Related issues \| )(.*)?[0-9]+(.*|\r|\n)?(\|)' | sed …
```

Fix issue parsing in issue tagging script

---

pkg/cmd/scan.go

We have decided to remove hint from there since they do not make sense anymore when displayed under Snyk CLI.
Another option could be to introduce a `--no-hint` flag or maybe reuse the actual `--quiet` flag.
Wrapping that in the `--quiet` flag have the drawback of loosing the progress bar and other useful diagnostic messages.

Remove hint from the diagnostic output

---

.github/CODEOWNERS

I think it can make sense to move the ownership of driftctl from the group to the team.
It will allow PR auto assign to be more accurate 🙏🏻
I'm not sure about the meaning for Snyk, I'll be sad but feel free to discard if it's not relevant.

Change code ownership to a more accurate team

---

pkg/resource/google/google_compute_subnetwork_test.go

This test has been failing recently and probably need a retry backoff strategy to overcome the cache issue.
See [this pipeline](https://app.circleci.com/pipelines/github/snyk/driftctl/4697/workflows/b1f9ae64-3138-4f58-bfd2-7d9f085d06e9/jobs/11203).

Add retry backoff to google_compute_subnetwork

---

pkg/cmd/scan.go
pkg/terraform/hcl/backend_test.go
pkg/terraform/hcl/cloud.go
pkg/terraform/hcl/cloud_test.go
pkg/terraform/hcl/hcl.go
pkg/terraform/hcl/hcl_test.go
pkg/terraform/hcl/testdata/cloud_block.tf
pkg/terraform/hcl/testdata/cloud_block_workspace.tf

| 🔗 Related issues | [CTX-331](https://snyksec.atlassian.net/browse/CTX-331)
| ❓ Documentation  | https://github.com/snyk/driftctl-docs/pull/247 
This PR adds state discovery for terraform cloud backend. This was tested with a TFC workspace, using both named and tag-targeted configurations.
**What changed**
- Moved `TestHCL_getCurrentWorkspaceName` test suite to `hcl_test.go` with no changes
- Added support for Cloud block in schema
- The backend block in HCL is not required anymore since Cloud and Backend are mutually exclusive
**Notes for the reviewers**
- Should we rename the terraform/hcl package to a more relevant name ? I think hcl is a …

State discovery for Terraform cloud

---

pkg/resource/google/google_storage_bucket_iam_member_test.go

This PR attempt to fix [this run](https://app.circleci.com/pipelines/github/snyk/driftctl/4747/workflows/0ba1f123-7d3b-480b-a922-e75c14f797ea/jobs/11426).

Add retry backoff to google_storage_bucket_iam_member acceptance test

---

pkg/resource/aws/aws_route_table_association_test.go

We've been seeing consistent failures for that resource, adding a retry.

chore: Retry route table association test

---

.circleci/config.yml

The time-cost of cleaning up after flakes, and investing in making flakes less frequent, isn't worth the benefit we get from these, given that we rarely make changes to this repo anymore.
We can run acceptance tests manually, against branches, by passing ACC_TESTS=1 in CircleCI if we feel the need, to test specific changes.

chore: disable nightly acceptance tests

---

go.mod
go.sum

| 🔗 Related issues | [IAC-3278](https://snyksec.atlassian.net/browse/IAC-3278)
Bumped github.com/golang-jwt/jwt/v4 to v4.5.2 to fix vuln CVE-2025-30204.
[IAC-3278]: https://snyksec.atlassian.net/browse/IAC-3278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: bumped golang-jwt to 4.5.2 [IAC-3278]
